import type { NativeProjectRuntimeOrderEvidence } from '../src/index.js';
import type { NativeProjectRuntimeOrderClassStaticBlockRecord } from '../src/index.js';
import type { NativeProjectRuntimeOrderEffectTargetRecord } from '../src/index.js';
import type { NativeProjectRuntimeOrderMutationTargetRecord } from '../src/index.js';
import type { NativeProjectRuntimeOrderProofEvidence } from '../src/index.js';
import type { NativeProjectRuntimeOrderPromiseChainRecord } from '../src/index.js';
import type { NativeProjectRuntimeOrderPromiseCombinatorRecord } from '../src/index.js';
import type { NativeProjectRuntimeOrderReachabilityRecord } from '../src/index.js';
import type { NativeProjectRuntimeOrderResourceManagementRecord } from '../src/index.js';
import type { NativeProjectRuntimeOrderYieldDelegationRecord } from '../src/index.js';

declare const runtimeOrder: NativeProjectRuntimeOrderEvidence;

runtimeOrder.runtimeScope satisfies string | undefined;
runtimeOrder.topLevelAwait satisfies boolean | undefined;
runtimeOrder.hostContext satisfies string | undefined;
runtimeOrder.importMetaMemberNames?.[0] satisfies string | undefined;
runtimeOrder.importMetaHostContext?.[0]?.memberPath?.[0] satisfies string | undefined;
runtimeOrder.classStaticBlockOrder?.[0] satisfies NativeProjectRuntimeOrderClassStaticBlockRecord | undefined;
runtimeOrder.classStaticBlockOrder?.[0]?.className satisfies string | undefined;
runtimeOrder.classStaticBlockOrder?.[0]?.statementCount satisfies number | undefined;
runtimeOrder.resourceManagementOrder?.[0] satisfies NativeProjectRuntimeOrderResourceManagementRecord | undefined;
runtimeOrder.resourceManagementOrder?.[0]?.declarationKind satisfies string | undefined;
runtimeOrder.resourceManagementOrder?.[0]?.disposalEffectEquivalenceClaim satisfies false | undefined;
runtimeOrder.effectTargetOrder?.[0] satisfies NativeProjectRuntimeOrderEffectTargetRecord | undefined;
runtimeOrder.effectTargetOrder?.[0]?.targetText satisfies string | undefined;
runtimeOrder.effectTargetOrder?.[0]?.taggedTemplate satisfies boolean | undefined;
runtimeOrder.effectTargetOrder?.[0]?.calleeName satisfies string | undefined;
runtimeOrder.effectTargetOrder?.[0]?.computedPropertyKeys?.[0] satisfies string | undefined;
runtimeOrder.effectTargetOrder?.[0]?.computedPropertyRuntimeEquivalenceClaim satisfies false | undefined;
runtimeOrder.effectTargetOrder?.[0]?.runtimeEquivalenceClaim satisfies false | undefined;
runtimeOrder.mutationTargetOrder?.[0] satisfies NativeProjectRuntimeOrderMutationTargetRecord | undefined;
runtimeOrder.mutationTargetOrder?.[0]?.targetText satisfies string | undefined;
runtimeOrder.mutationTargetOrder?.[0]?.methodName satisfies string | undefined;
runtimeOrder.mutationTargetOrder?.[0]?.methodComputed satisfies boolean | undefined;
runtimeOrder.mutationTargetOrder?.[0]?.computedMethodName satisfies string | undefined;
runtimeOrder.mutationTargetOrder?.[0]?.computedMethodRuntimeEquivalenceClaim satisfies false | undefined;
runtimeOrder.mutationTargetOrder?.[0]?.computedPropertyKeys?.[0] satisfies string | undefined;
runtimeOrder.mutationTargetOrder?.[0]?.computedPropertyStatic satisfies boolean | undefined;
runtimeOrder.mutationTargetOrder?.[0]?.computedPropertyRuntimeEquivalenceClaim satisfies false | undefined;
runtimeOrder.mutationTargetOrder?.[0]?.runtimeEquivalenceClaim satisfies false | undefined;
runtimeOrder.reachabilityOrder?.[0] satisfies NativeProjectRuntimeOrderReachabilityRecord | undefined;
runtimeOrder.reachabilityOrder?.[0]?.completionKind satisfies string | undefined;
runtimeOrder.reachabilityOrder?.[0]?.elseIfLines?.[0] satisfies number | undefined;
runtimeOrder.reachabilityOrder?.[0]?.branchLineNumbers?.[0] satisfies number | undefined;
runtimeOrder.reachabilityOrder?.[0]?.branchCompletionKinds?.[0] satisfies string | undefined;
runtimeOrder.reachabilityOrder?.[0]?.fullPathReachabilityClaim satisfies false | undefined;
runtimeOrder.sameLinePromiseCombinator?.[0] satisfies NativeProjectRuntimeOrderPromiseCombinatorRecord | undefined;
runtimeOrder.sameLinePromiseCombinator?.[0]?.runtimeEquivalenceClaim satisfies false | undefined;
runtimeOrder.sameLinePromiseChain?.[0] satisfies NativeProjectRuntimeOrderPromiseChainRecord | undefined;
runtimeOrder.sameLinePromiseChain?.[0]?.handlerMethodName satisfies string | undefined;
runtimeOrder.sameLinePromiseChain?.[0]?.handlerStepOrdinal satisfies number | undefined;
runtimeOrder.sameLinePromiseChain?.[0]?.handlerExecutionEquivalenceClaim satisfies false | undefined;
runtimeOrder.exitOrder?.[0] satisfies NativeProjectRuntimeOrderYieldDelegationRecord | undefined;
runtimeOrder.exitOrder?.[0]?.delegationKind satisfies string | undefined;
runtimeOrder.exitOrder?.[0]?.delegatedIterableText satisfies string | undefined;
runtimeOrder.exitOrder?.[0]?.iteratorProtocolEquivalenceClaim satisfies false | undefined;
runtimeOrder.exitOrder?.[0]?.delegatedCompletionPropagationClaim satisfies false | undefined;

declare const proofEvidence: NativeProjectRuntimeOrderProofEvidence;

proofEvidence.schema satisfies 'frontier.lang.runtimeOrderProofEvidence.v1' | string;
proofEvidence.status satisfies 'passed' | 'verified' | string;
proofEvidence.proofLevel satisfies 'runtime-order-only' | 'executable-effect-observation' | string | undefined;
proofEvidence.sourcePath satisfies string;
proofEvidence.baseSourceHash satisfies string | undefined;
proofEvidence.workerSourceHash satisfies string | undefined;
proofEvidence.headSourceHash satisfies string | undefined;
proofEvidence.regionKey satisfies string | undefined;
proofEvidence.conflictKey satisfies string | undefined;
proofEvidence.regionKind satisfies string | undefined;
proofEvidence.runtimeKind satisfies string | undefined;
proofEvidence.signatureHash satisfies string | undefined;
proofEvidence.importMetaHostContextHash satisfies string | undefined;
proofEvidence.hostContextMemberHash satisfies string | undefined;
proofEvidence.importMetaHostResolutionTraceHash satisfies string | undefined;
proofEvidence.hostContextResolutionTraceHash satisfies string | undefined;
proofEvidence.importMetaHostRuntimeTraceHash satisfies string | undefined;
proofEvidence.importMetaHostContextEquivalenceClaim satisfies false | undefined;
proofEvidence.hostRuntimeResolutionEquivalenceClaim satisfies false | undefined;
proofEvidence.promiseCombinatorOrderHash satisfies string | undefined;
proofEvidence.promiseConcurrencyOrderHash satisfies string | undefined;
proofEvidence.promiseCombinatorConcurrencyTraceHash satisfies string | undefined;
proofEvidence.promiseConcurrencyTraceHash satisfies string | undefined;
proofEvidence.promiseCombinatorSettlementTraceHash satisfies string | undefined;
proofEvidence.promiseSettlementTraceHash satisfies string | undefined;
proofEvidence.promiseCombinatorElementOrderTraceHash satisfies string | undefined;
proofEvidence.promiseElementOrderTraceHash satisfies string | undefined;
proofEvidence.promiseAllSettlementTraceHash satisfies string | undefined;
proofEvidence.promiseCombinatorAllSettlementTraceHash satisfies string | undefined;
proofEvidence.promiseAllSettledRecordTraceHash satisfies string | undefined;
proofEvidence.promiseCombinatorAllSettledRecordTraceHash satisfies string | undefined;
proofEvidence.promiseRaceFirstSettlementTraceHash satisfies string | undefined;
proofEvidence.promiseCombinatorRaceFirstSettlementTraceHash satisfies string | undefined;
proofEvidence.promiseAnyFirstFulfillmentTraceHash satisfies string | undefined;
proofEvidence.promiseCombinatorAnyFirstFulfillmentTraceHash satisfies string | undefined;
proofEvidence.promiseChainOrderHash satisfies string | undefined;
proofEvidence.promiseHandlerOrderHash satisfies string | undefined;
proofEvidence.promiseChainHandlerOrderTraceHash satisfies string | undefined;
proofEvidence.promiseHandlerOrderTraceHash satisfies string | undefined;
proofEvidence.promiseChainRejectionFlowTraceHash satisfies string | undefined;
proofEvidence.promiseRejectionFlowTraceHash satisfies string | undefined;
proofEvidence.promiseChainFinalizerTraceHash satisfies string | undefined;
proofEvidence.promiseFinalizerTraceHash satisfies string | undefined;
proofEvidence.promiseCombinatorRuntimeEquivalenceClaim satisfies false | undefined;
proofEvidence.promiseConcurrencyEquivalenceClaim satisfies false | undefined;
proofEvidence.promiseSettlementEquivalenceClaim satisfies false | undefined;
proofEvidence.promiseElementOrderEquivalenceClaim satisfies false | undefined;
proofEvidence.promiseChainRuntimeEquivalenceClaim satisfies false | undefined;
proofEvidence.promiseHandlerExecutionEquivalenceClaim satisfies false | undefined;
proofEvidence.promiseRejectionFlowEquivalenceClaim satisfies false | undefined;
proofEvidence.promiseFinalizerEquivalenceClaim satisfies false | undefined;
proofEvidence.resourceManagementDisposalOrderHash satisfies string | undefined;
proofEvidence.resourceManagementAsyncDisposalTraceHash satisfies string | undefined;
proofEvidence.disposalEffectEquivalenceClaim satisfies false | undefined;
proofEvidence.generatorProtocolOrderHash satisfies string | undefined;
proofEvidence.iteratorProtocolOrderHash satisfies string | undefined;
proofEvidence.asyncGeneratorProtocolOrderHash satisfies string | undefined;
proofEvidence.asyncIteratorProtocolOrderHash satisfies string | undefined;
proofEvidence.generatorProtocolTraceHash satisfies string | undefined;
proofEvidence.iteratorProtocolTraceHash satisfies string | undefined;
proofEvidence.generatorIteratorTraceHash satisfies string | undefined;
proofEvidence.delegatedCompletionTraceHash satisfies string | undefined;
proofEvidence.generatorCompletionTraceHash satisfies string | undefined;
proofEvidence.asyncGeneratorProtocolTraceHash satisfies string | undefined;
proofEvidence.asyncIteratorProtocolTraceHash satisfies string | undefined;
proofEvidence.asyncGeneratorCancellationTraceHash satisfies string | undefined;
proofEvidence.asyncIteratorCancellationTraceHash satisfies string | undefined;
proofEvidence.asyncGeneratorBackpressureTraceHash satisfies string | undefined;
proofEvidence.asyncIteratorBackpressureTraceHash satisfies string | undefined;
proofEvidence.generatorRuntimeEquivalenceClaim satisfies false | undefined;
proofEvidence.iteratorProtocolEquivalenceClaim satisfies false | undefined;
proofEvidence.delegatedCompletionPropagationClaim satisfies false | undefined;
proofEvidence.asyncGeneratorRuntimeEquivalenceClaim satisfies false | undefined;
proofEvidence.asyncIteratorProtocolEquivalenceClaim satisfies false | undefined;
proofEvidence.asyncIteratorCancellationEquivalenceClaim satisfies false | undefined;
proofEvidence.asyncIteratorBackpressureEquivalenceClaim satisfies false | undefined;
proofEvidence.classStaticBlockOrderHash satisfies string | undefined;
proofEvidence.staticInitializationOrderHash satisfies string | undefined;
proofEvidence.classStaticBlockExecutionTraceHash satisfies string | undefined;
proofEvidence.staticInitializationTraceHash satisfies string | undefined;
proofEvidence.classStaticBlockEffectTraceHash satisfies string | undefined;
proofEvidence.classStaticBlockRuntimeEquivalenceClaim satisfies false | undefined;
proofEvidence.staticInitializationEquivalenceClaim satisfies false | undefined;
proofEvidence.topLevelAwaitOrderHash satisfies string | undefined;
proofEvidence.topLevelAwaitSuspensionOrderHash satisfies string | undefined;
proofEvidence.topLevelAwaitSuspensionTraceHash satisfies string | undefined;
proofEvidence.moduleEvaluationTraceHash satisfies string | undefined;
proofEvidence.topLevelAwaitSuspensionEquivalenceClaim satisfies false | undefined;
proofEvidence.moduleEvaluationOrderEquivalenceClaim satisfies false | undefined;
proofEvidence.autoMergeClaim satisfies false;
proofEvidence.semanticEquivalenceClaim satisfies false;
proofEvidence.runtimeEquivalenceClaim satisfies false;
