import { assert, publicValueExportsFromDeclaration } from './helpers.mjs';
import { compilerApi } from './compiler-api.mjs';

const publicRuntimeExports = Object.keys(compilerApi).sort();
const publicDeclarationExports = publicValueExportsFromDeclaration(new URL('../../dist/index.d.ts', import.meta.url));
assert.deepEqual(publicRuntimeExports, publicDeclarationExports);
for (const requiredExport of [
  'attachUniversalDialectRegistry',
  'NativeImportFeatureEvidencePolicies',
  'NativeParserAstFormats',
  'NativeParserAstFormatProfiles',
  'NativeParserFeatureCategories',
  'NativeParserFeatureCoverageStatuses',
  'NativeImportRegionTaxonomyKinds',
  'ProjectionTargetLossClasses',
  'ProjectionReadinessStatuses',
  'LanguageAdapterPackageContracts',
  'LanguageAdapterPackageReleaseReadinessStatuses',
  'SemanticMergeConflictClasses',
  'SemanticMergeCandidateProjectionRisks',
  'SemanticPatchBundleAdmissionStatuses',
  'SemanticHistoryAdmissionStatuses',
  'SemanticHistoryConflictReasons',
  'SemanticHistoryOverlapKinds',
  'SemanticHistoryReviewerStatuses',
  'UniversalDialectConstructKinds',
  'UniversalDialectProjectionDispositions',
  'createNativeImportResultContract',
  'createLanguageAdapterPackageContract',
  'createNativeParserAstFormatMatrix',
  'createNativeParserFeatureMatrix',
  'createNativeRoundtripEvidence',
  'createProjectImportAdmissionRecord',
  'createProjectionReadinessMatrix',
  'createCSharpRoslynNativeImporterAdapter',
  'createClangAstNativeImporterAdapter',
  'createGoAstNativeImporterAdapter',
  'createJavaAstNativeImporterAdapter',
  'createKotlinPsiNativeImporterAdapter',
  'createSwiftSyntaxNativeImporterAdapter',
  'createPythonAstNativeImporterAdapter',
  'createRustSynNativeImporterAdapter',
  'createProjectionTargetLossMatrix',
  'createSemanticHistoryRecord',
  'createSemanticMergeCandidateAdmissionRecord',
  'createSemanticPatchBundleRecord',
  'createUniversalCapabilityMatrix',
  'createUniversalConversionArtifacts',
  'createUniversalConversionPlan',
  'createUniversalDialectRecord',
  'createUniversalDialectRegistry',
  'createUniversalExternRecord',
  'decorateSemanticMergeCandidateForAdmission',
  'classifyNativeImportRoundtripReadiness',
  'compileNativeSource',
  'createSemanticImportSidecar',
  'createSemanticSlice',
  'createSemanticSliceAdmissionRecord',
  'diffNativeSourceImports',
  'diffNativeSources',
  'emitForTargetWithSourceMap',
  'getLanguageAdapterPackageContract',
  'getNativeImportFeatureEvidencePolicy',
  'getNativeParserAstFormatProfile',
  'queryLanguageAdapterPackageContracts',
  'queryNativeParserFeatureMatrix',
  'queryProjectionReadinessMatrix',
  'querySemanticHistoryRecordOverlaps',
  'querySemanticMergeCandidateAdmissionOverlaps',
  'querySemanticPatchBundleRecords',
  'querySemanticMergeConflictClasses',
  'queryUniversalConversionArtifacts',
  'queryUniversalConversionPlan',
  'readSemanticSliceJson',
  'semanticMergeConflictRiskScore',
  'semanticMergeCandidateReadinessSortKey',
  'semanticHistoryRecordsConflict',
  'semanticHistoryRecordsOverlap',
  'sortSemanticMergeCandidateAdmissionRecords',
  'sortSemanticMergeCandidatesByConflictRisk',
  'summarizeLanguageAdapterPackageContracts',
  'summarizeSemanticMergeConflicts',
  'summarizeUniversalDialectRegistry',
  'testSemanticSlice',
  'writeSemanticSliceJson',
  'ExternalSemanticIndexFormats',
  'importExternalSemanticIndex',
  'importNativeSource',
  'importNativeProject',
  'renderTargetAstWithSourceMap',
  'runNativeTargetProjectionAdapter'
]) {
  assert.equal(publicRuntimeExports.includes(requiredExport), true, `missing public export ${requiredExport}`);
}
