import { measureFrontierCompile } from './compile-suite.mjs';
import { collectNativeImports } from './native-import-suite.mjs';
import { measureNativeMatrices } from './native-matrix-suite.mjs';
import { measureNativeTransformations } from './native-transform-suite.mjs';
import { measureSourceChangeSuites } from './source-change-suite.mjs';

const compileMetrics = measureFrontierCompile();
const importMetrics = await collectNativeImports();
const matrixMetrics = measureNativeMatrices(importMetrics.nativeImportResults, importMetrics.adapters);
const transformMetrics = measureNativeTransformations(importMetrics.nativeImportResults);
const sourceChangeMetrics = measureSourceChangeSuites();

console.log(JSON.stringify({
  compiles: 250,
  bytes: compileMetrics.bytes,
  compileDurationMs: Number(compileMetrics.compileDurationMs.toFixed(2)),
  nativeImports: importMetrics.nativeImportResults.length,
  nativeSymbols: importMetrics.nativeSymbols,
  nativeImportDurationMs: Number(importMetrics.nativeImportDurationMs.toFixed(2)),
  coverageMatrixLanguages: matrixMetrics.coverageMatrix.summary.languages,
  coverageMatrixImports: matrixMetrics.coverageMatrix.summary.imports,
  adapterCoverageSummaries: matrixMetrics.coverageMatrix.summary.adapterCoverage.total,
  adapterCoverageSourceRanges: matrixMetrics.coverageMatrix.summary.adapterCoverage.effective.sourceRanges ?? 0,
  adapterCoverageTokenGaps: matrixMetrics.coverageMatrix.summary.adapterCoverage.gaps.tokens ?? 0,
  adapterCoverageReferenceGaps: matrixMetrics.coverageMatrix.summary.adapterCoverage.gaps.references ?? 0,
  coverageMatrixDurationMs: Number(matrixMetrics.coverageMatrixDurationMs.toFixed(2)),
  parserFormatMatrixFormats: matrixMetrics.parserFormatMatrix.summary.formats,
  parserFormatMatrixImports: matrixMetrics.parserFormatMatrix.summary.imports,
  parserFormatMatrixNativeAstNodes: matrixMetrics.parserFormatMatrix.summary.nativeAstNodes,
  parserFormatMatrixDurationMs: Number(matrixMetrics.parserFormatMatrixDurationMs.toFixed(2)),
  parserFeatureMatrixParsers: matrixMetrics.parserFeatureMatrix.summary.parsers,
  parserFeatureMatrixMergeReady: matrixMetrics.parserFeatureMatrix.summary.mergeReady,
  parserFeatureMatrixSyntaxFull: matrixMetrics.parserFeatureMatrix.summary.byFeatureStatus.syntax?.full ?? 0,
  parserFeatureQueryMergeReady: matrixMetrics.parserFeatureQuery.merge.mergeReady,
  parserFeatureMatrixDurationMs: Number(matrixMetrics.parserFeatureMatrixDurationMs.toFixed(2)),
  projectionMatrixLanguages: matrixMetrics.projectionLossMatrix.summary.languages,
  projectionMatrixMissingAdapters: matrixMetrics.projectionLossMatrix.summary.missingAdapters,
  projectionMatrixUnsupportedTargetFeatures: matrixMetrics.projectionLossMatrix.summary.unsupportedTargetFeatures,
  projectionMatrixDurationMs: Number(matrixMetrics.projectionMatrixDurationMs.toFixed(2)),
  universalMatrixLanguages: matrixMetrics.universalCapabilityMatrix.summary.languages,
  universalMatrixImports: matrixMetrics.universalCapabilityMatrix.summary.imports,
  universalMatrixBlockedLanguages: matrixMetrics.universalCapabilityMatrix.summary.blockedLanguages,
  universalMatrixMissingAdapters: matrixMetrics.universalCapabilityMatrix.summary.missingAdapters,
  universalMatrixDurationMs: Number(matrixMetrics.universalMatrixDurationMs.toFixed(2)),
  sourcePreservationRecords: transformMetrics.sourcePreservationRecords,
  sourcePreservationTokens: transformMetrics.sourcePreservationTokens,
  sourcePreservationDurationMs: Number(transformMetrics.sourcePreservationDurationMs.toFixed(2)),
  semanticSidecars: transformMetrics.semanticSidecars,
  sidecarOwnershipRegions: transformMetrics.sidecarOwnershipRegions,
  sidecarDurationMs: Number(transformMetrics.sidecarDurationMs.toFixed(2)),
  semanticSlices: transformMetrics.semanticSlices,
  sliceDurationMs: Number(transformMetrics.sliceDurationMs.toFixed(2)),
  sliceGateDurationMs: Number(transformMetrics.sliceGateDurationMs.toFixed(2)),
  sliceAdmissionDurationMs: Number(transformMetrics.sliceAdmissionDurationMs.toFixed(2)),
  sliceSourceMapLinks: transformMetrics.sliceSourceMapLinks,
  sliceConflictKeys: transformMetrics.sliceConflictKeys,
  sliceGateFailures: transformMetrics.sliceGateFailures,
  sliceAdmissions: transformMetrics.sliceAdmissions,
  sliceAdmissionRejected: transformMetrics.sliceAdmissionRejected,
  conversionPlanRoutes: transformMetrics.conversionPlanRoutes,
  conversionPlanBlocked: transformMetrics.conversionPlanBlocked,
  conversionPlanDurationMs: Number(transformMetrics.conversionPlanDurationMs.toFixed(2)),
  conversionArtifacts: transformMetrics.conversionArtifacts,
  conversionArtifactHistories: transformMetrics.conversionArtifactHistories,
  conversionArtifactPatchBundles: transformMetrics.conversionArtifactPatchBundles,
  conversionArtifactAdmissionRecords: transformMetrics.conversionArtifactAdmissionRecords,
  conversionArtifactMergeReady: transformMetrics.conversionArtifactMergeReady,
  conversionArtifactNeedsEvidence: transformMetrics.conversionArtifactNeedsEvidence,
  conversionArtifactNeedsAdapter: transformMetrics.conversionArtifactNeedsAdapter,
  conversionArtifactNeedsReview: transformMetrics.conversionArtifactNeedsReview,
  conversionArtifactAdmissionBlocked: transformMetrics.conversionArtifactAdmissionBlocked,
  conversionArtifactLowRisk: transformMetrics.conversionArtifactLowRisk,
  conversionArtifactMediumRisk: transformMetrics.conversionArtifactMediumRisk,
  conversionArtifactHighRisk: transformMetrics.conversionArtifactHighRisk,
  conversionArtifactQueued: transformMetrics.conversionArtifactQueued,
  conversionArtifactAdmissionReasonCodes: transformMetrics.conversionArtifactAdmissionReasonCodes,
  conversionArtifactAdmissionMissingEvidence: transformMetrics.conversionArtifactAdmissionMissingEvidence,
  conversionArtifactAdmissionBlockers: transformMetrics.conversionArtifactAdmissionBlockers,
  conversionArtifactAdmissionReviewReasons: transformMetrics.conversionArtifactAdmissionReviewReasons,
  conversionArtifactAdmissionEvidenceIds: transformMetrics.conversionArtifactAdmissionEvidenceIds,
  conversionArtifactAdmissionProofIds: transformMetrics.conversionArtifactAdmissionProofIds,
  conversionArtifactsDurationMs: Number(transformMetrics.conversionArtifactsDurationMs.toFixed(2)),
  featureEvidencePolicyMatches: transformMetrics.featureEvidencePolicyMatches,
  featureEvidenceDurationMs: Number(transformMetrics.featureEvidenceDurationMs.toFixed(2)),
  nativeProjections: transformMetrics.nativeProjections,
  projectionBytes: transformMetrics.projectionBytes,
  projectionDurationMs: Number(transformMetrics.projectionDurationMs.toFixed(2)),
  nativeCompiles: transformMetrics.nativeCompiles,
  nativeCompileBytes: transformMetrics.nativeCompileBytes,
  nativeCompileSourceMaps: transformMetrics.nativeCompileSourceMaps,
  nativeCompileSourceMapMappings: transformMetrics.nativeCompileSourceMapMappings,
  nativeCompileBlocked: transformMetrics.nativeCompileBlocked,
  nativeCompileDurationMs: Number(transformMetrics.nativeCompileDurationMs.toFixed(2)),
  nativeTargetAdapterCompiles: transformMetrics.nativeTargetAdapterCompiles,
  nativeTargetAdapterBytes: transformMetrics.nativeTargetAdapterBytes,
  nativeTargetAdapterSourceMaps: transformMetrics.nativeTargetAdapterSourceMaps,
  nativeTargetAdapterDurationMs: Number(transformMetrics.nativeTargetAdapterDurationMs.toFixed(2)),
  regionScanImports: sourceChangeMetrics.regionScanImports,
  regionScanSymbols: sourceChangeMetrics.regionScanSymbols,
  regionScanDependencyRelations: sourceChangeMetrics.regionScanDependencyRelations,
  regionScanOwnershipRegions: sourceChangeMetrics.regionScanOwnershipRegions,
  regionScanDurationMs: Number(sourceChangeMetrics.regionScanDurationMs.toFixed(2)),
  changeProjectionSets: sourceChangeMetrics.changeProjectionSets,
  changedRegionProjections: sourceChangeMetrics.changedRegionProjections,
  changedRegionProjectionSourceMapLinks: sourceChangeMetrics.changedRegionProjectionSourceMapLinks,
  changeProjectionDurationMs: Number(sourceChangeMetrics.changeProjectionDurationMs.toFixed(2)),
  externalSemanticImports: sourceChangeMetrics.externalSemanticImports,
  externalSemanticSymbols: sourceChangeMetrics.externalSemanticSymbols,
  externalSemanticMappings: sourceChangeMetrics.externalSemanticMappings,
  externalSemanticDurationMs: Number(sourceChangeMetrics.externalSemanticDurationMs.toFixed(2))
}));
