import type { JsTsProjectMergeProofLevel } from './js-ts-project-merge-proof-levels.js';
import type { JsTsProjectSafeMergeMissingEvidenceTelemetry } from './js-ts-project-merge-confidence.js';

export type JsTsProjectSourceTextMergeCandidateStatus = 'passed' | 'failed' | 'absent' | string;
export type JsTsProjectMergeSummaryProofStatus = 'passed' | 'failed' | 'skipped' | 'unknown' | 'missing' | 'absent' | string;

export interface JsTsProjectSafeMergeSummary {
  readonly files: number; readonly mergedFiles: number; readonly blockedFiles: number; readonly outputFiles: number;
  readonly sourceTextMergeCandidateFiles: number; readonly sourceTextMergeBlockedFiles: number; readonly sourceTextMergeOutputFiles: number; readonly sourceTextMergeCandidateStatus: JsTsProjectSourceTextMergeCandidateStatus;
  readonly htmlFiles:number; readonly cssFiles:number; readonly svgFiles:number; readonly htmlCssFiles:number; readonly htmlMergedFiles:number; readonly cssMergedFiles:number; readonly svgMergedFiles:number; readonly htmlCssMergedFiles:number; readonly htmlBlockedFiles:number; readonly cssBlockedFiles:number; readonly svgBlockedFiles:number; readonly htmlCssBlockedFiles:number; readonly htmlCssBrowserRuntimeProofs:number; readonly htmlCssBrowserRuntimeProofAdmittedFiles:number; readonly htmlCssBrowserRuntimeProofBlockedFiles:number; readonly svgBrowserRuntimeProofs:number; readonly svgBrowserRuntimeProofBlockedFiles:number;
  readonly htmlParserEvidenceFiles:number; readonly cssParserEvidenceFiles:number; readonly svgParserEvidenceFiles:number; readonly htmlCssParserEvidenceFiles:number; readonly htmlParserEvidenceFailedFiles:number; readonly cssParserEvidenceFailedFiles:number; readonly svgParserEvidenceFailedFiles:number; readonly htmlCssParserEvidenceFailedFiles:number;
  readonly svgReferenceGraphEvidenceFiles:number; readonly svgReferenceGraphEvidenceFailedFiles:number; readonly svgReferenceGraphDefinitionRecords:number; readonly svgReferenceGraphReferenceRecords:number; readonly svgReferenceGraphMissingReferenceRecords:number;
  readonly htmlIdentityEvidenceFiles:number; readonly svgIdentityEvidenceFiles:number; readonly cssSelectorTargetEvidenceFiles:number; readonly htmlCssStructuralTargetEvidenceFiles:number; readonly cssSelectorTargetGraphEvidenceFiles:number; readonly cssSelectorSpecificityEvidenceFiles:number; readonly cssSelectorTargetMoveFiles:number; readonly htmlExplicitIdentityEvidenceFiles:number; readonly htmlPathOnlyIdentityResidualFiles:number; readonly htmlDuplicateIdentityEvidenceFiles:number; readonly htmlDuplicateIdentityKeys:number; readonly svgExplicitIdentityEvidenceFiles:number; readonly svgPathOnlyIdentityResidualFiles:number; readonly svgDuplicateIdentityEvidenceFiles:number; readonly svgDuplicateIdentityKeys:number; readonly htmlRuntimeBoundaryEvidenceFiles:number; readonly htmlFrameworkBoundaryEvidenceFiles:number; readonly htmlProofGapBlockedFiles:number; readonly svgRuntimeBoundaryEvidenceFiles:number; readonly svgFrameworkBoundaryEvidenceFiles:number; readonly svgProofGapBlockedFiles:number; readonly htmlClassTokenMergeFiles:number; readonly htmlClassTokenMergeEvidenceRecords:number; readonly htmlTokenListMergeFiles:number; readonly htmlTokenListMergeEvidenceRecords:number; readonly htmlUnkeyedStructuralAddFiles:number; readonly htmlUnkeyedStructuralAddEvidenceRecords:number; readonly htmlUnkeyedStructuralDeleteFiles:number; readonly htmlUnkeyedStructuralDeleteEvidenceRecords:number; readonly htmlUnkeyedStructuralMoveFiles:number; readonly htmlUnkeyedStructuralMoveEvidenceRecords:number; readonly htmlIdentityEvidenceFailedFiles:number; readonly svgIdentityEvidenceFailedFiles:number; readonly cssSelectorTargetConflictFiles:number; readonly htmlCssStructuralTargetEvidenceFailedFiles:number; readonly cssSelectorTargetRebasedFiles:number;
  readonly svgStructuralAddFiles:number; readonly svgStructuralDeleteFiles:number; readonly svgStructuralMoveFiles:number;
  readonly cssScopedCascadeFiles:number; readonly cssScopedCascadeEvidenceFiles:number; readonly cssScopedCascadeShapeEvidenceFiles:number; readonly cssScopedCascadeBlockedFiles:number; readonly cssDuplicateCascadeKeyBlockedFiles:number; readonly cssOrderedCascadeOccurrenceEvidenceFiles:number; readonly cssOrderedCascadeOccurrenceEvidenceRecords:number; readonly cssShorthandExpansionEvidenceFiles:number; readonly cssDeterministicShorthandExpansionFiles:number; readonly cssShorthandExpansionBlockedFiles:number; readonly cssDependencySurfaceFiles:number; readonly cssDependencyGraphEvidenceFiles:number; readonly cssDependencyGraphMissingProofFiles:number; readonly cssDependencyGraphBlockedFiles:number; readonly cssRuntimeDescriptorFiles:number; readonly cssRuntimeDescriptorEvidenceFiles:number; readonly cssRuntimeDescriptorBlockedFiles:number; readonly cssPropertyDescriptorFiles:number; readonly cssPropertyDescriptorEvidenceFiles:number; readonly cssPageDescriptorFiles:number; readonly cssPageDescriptorEvidenceFiles:number;
  readonly packageManagementFiles:number; readonly packageJsonFiles:number; readonly packageLockfileFiles:number; readonly packageManagementMergedFiles:number; readonly packageManagementBlockedFiles:number; readonly packageIntentMergeFiles:number; readonly packageGraphEvidenceFiles:number; readonly packageLockfileRegeneratedFiles:number; readonly packageLockfileUnchangedFiles:number; readonly packageManagementProofs:number; readonly packageLockfileRegenerationProofs:number; readonly packagePublicSurfaceProofs:number; readonly packagePeerResolutionProofs:number; readonly packageInstallScriptProofs:number; readonly packageWorkspaceProofs:number; readonly packageManagerMigrationProofs:number; readonly packageDependencyRangeConflictFiles:number; readonly packagePeerResolutionBlockedFiles:number; readonly packageInstallScriptBlockedFiles:number; readonly packagePublicSurfaceBlockedFiles:number; readonly packageWorkspaceBlockedFiles:number; readonly packageManagerMigrationBlockedFiles:number; readonly packageLockfileRegenerationBlockedFiles:number; readonly packageScriptConflictFiles:number; readonly packageJsonParseErrorFiles:number; readonly packageManagementConflictSignals:number; readonly canvasSurfaceFiles:number; readonly htmlCanvasElementFiles:number; readonly htmlCanvasStaticMergedFiles:number; readonly canvasRuntimeSurfaceFiles:number; readonly canvasRuntimeProofs:number; readonly canvasRuntimeProofFiles:number; readonly canvasRuntimeBlockedFiles:number; readonly canvasDrawingRuntimeBlockedFiles:number; readonly canvasOffscreenWorkerBlockedFiles:number; readonly canvasOffscreenWorkerProofs:number;
  readonly projectGraphConflicts: number; readonly projectGraphDeltaEvidenceIncluded: number; readonly projectGraphEvidenceIncluded: number; readonly outputProjectGraphConflicts:number; readonly projectGraphCssModuleUseSiteConflicts:number; readonly projectGraphDeltaConflicts: number; readonly projectGraphCssModuleUseSiteBlockers:number; readonly projectGraphCssModuleUseSiteProofBlockers:number; readonly projectGraphCssModuleGeneratedClassNameMapBlockers:number; readonly projectGraphCssModuleBundlerTransformIdentityBlockers:number; readonly projectGraphCssModuleSourceMapIdentityBlockers:number; readonly projectGraphCssModuleTransformProofBlockers:number; readonly projectGraphLimitConflicts: number; readonly projectGraphCssModuleUseSiteGraphs:number; readonly projectGraphCssModuleUseSites:number; readonly projectGraphCssModuleImportBindings:number; readonly projectGraphPublicContractConflicts: number; readonly projectGraphSourceSpanConflicts: number;
  readonly projectGraphCompilerTypeConflicts: number; readonly projectGraphRuntimeRegionConflicts: number; readonly projectGraphScopeUseDefConflicts: number; readonly projectGraphJsxPropConflicts: number; readonly projectGraphJsxRenderRiskConflicts: number; readonly projectGraphReExportIdentityConflicts: number; readonly projectGraphModuleDeclarationShapeConflicts: number; readonly projectGraphExportAssignmentShapeConflicts: number;
  readonly projectGraphImportAttributeConflicts: number; readonly projectGraphImportTargetConflicts: number; readonly outputDiagnostics: number; readonly outputDiagnosticConflicts: number; readonly outputDiagnosticErrors: number; readonly outputDiagnosticWarnings: number; readonly outputDeclarations: number; readonly outputDeclarationBytes: number; readonly outputDeclarationConflicts: number; readonly outputDeclarationDiagnosticErrors: number; readonly outputQualityGates: number; readonly outputQualityGateConflicts: number;
  readonly proofEvidenceRecords: number; readonly proofEvidencePassed: number; readonly proofEvidenceFailed: number; readonly proofEvidenceSkipped: number; readonly proofEvidenceUnknown: number; readonly proofEvidenceMissing: number; readonly proofEvidenceMissingLevels: readonly JsTsProjectMergeProofLevel[]; readonly proofEvidenceMissingSignals: readonly string[]; readonly proofEvidenceNextMissingCode?: string; readonly proofEvidenceNextMissingLevel?: JsTsProjectMergeProofLevel; readonly proofEvidenceNextMissingScope?: string; readonly proofEvidenceLevelStatuses: Readonly<Record<string,JsTsProjectMergeSummaryProofStatus>>; readonly proofSyntaxIdentityStatus: JsTsProjectMergeSummaryProofStatus; readonly proofSourceSpanRoundtripStatus: JsTsProjectMergeSummaryProofStatus; readonly proofSemanticEditReplayCleanStatus: JsTsProjectMergeSummaryProofStatus; readonly proofDiagnosticsStatus: JsTsProjectMergeSummaryProofStatus; readonly proofDeclarationOutputStatus: JsTsProjectMergeSummaryProofStatus; readonly proofFocusedTestStatus: JsTsProjectMergeSummaryProofStatus; readonly proofSemanticEquivalenceStatus: JsTsProjectMergeSummaryProofStatus; readonly semanticEquivalenceLevel: 'semantic-equivalence-unknown' | string; readonly semanticEquivalenceClaim: boolean;
  readonly evidenceRecords: number; readonly passedEvidenceRecords: number; readonly failedEvidenceRecords: number; readonly unknownEvidenceRecords: number; readonly confidenceScore: number; readonly confidenceLevel: string; readonly confidenceDimensions: Readonly<Record<string,string>>; readonly missingEvidenceMatrix: JsTsProjectSafeMergeMissingEvidenceTelemetry; readonly routingCalibration?: Readonly<Record<string,unknown>>; readonly missingSignals: number; readonly admissionMatrixPartialRows: number;
  readonly nextMissingEvidenceCode?: string; readonly nextMissingEvidenceKind?: string; readonly nextMissingEvidenceScope?: string; readonly nextMissingProofLevel?: string; readonly nextMissingEvidenceAction?: string; readonly nextMissingEvidenceRouteId?: string; readonly nextMissingEvidenceRouteLane?: string; readonly nextMissingEvidenceRouteNext?: string;
  readonly projectMoveRenameClassifications: number; readonly projectFileMoveRenameClassifications: number; readonly projectSymbolMoveClassifications: number; readonly projectExportedSymbolMoveClassifications: number; readonly projectImportedSymbolMoveClassifications: number; readonly projectSymbolMoveAdmissions: number; readonly projectExportedSymbolMoveAdmissions: number; readonly projectImportedSymbolMoveAdmissions: number; readonly projectCrossFileSymbolRenameClassifications: number; readonly projectCrossFileSymbolRenameAdmissions: number;
  readonly projectSplitMergeClassifications: number; readonly projectModuleSplitClassifications: number; readonly projectModuleMergeClassifications: number; readonly projectClassSplitClassifications: number; readonly projectClassMergeClassifications: number; readonly projectSplitMergeAdmissions: number; readonly projectModuleSplitAdmissions: number; readonly projectModuleMergeAdmissions: number; readonly projectClassSplitAdmissions: number; readonly projectClassMergeAdmissions: number;
  readonly semanticArtifactFiles: number; readonly operations: Readonly<Record<string,number>>;
}
