export interface SemanticPatchBundleRecordIndex {
  readonly baseHashes: readonly string[];
  readonly targetHashes: readonly string[];
  readonly sourceHashes: readonly string[];
  readonly sourcePaths: readonly string[];
  readonly regionKeys: readonly string[];
  readonly regionKinds: readonly string[];
  readonly conflictKeys: readonly string[];
  readonly sourceMapIds: readonly string[];
  readonly sourceMapMappingIds: readonly string[];
  readonly sourceMapLinkIds: readonly string[];
  readonly evidenceIds: readonly string[];
  readonly proofIds: readonly string[];
  readonly lineageResolutionIds: readonly string[];
  readonly lineageEventIds: readonly string[];
  readonly lineageSourcePaths: readonly string[];
  readonly lineageEvidenceIds: readonly string[];
  readonly lineageProofIds: readonly string[];
  readonly lineageReasonCodes: readonly string[];
  readonly historyIds: readonly string[];
  readonly semanticOperationIds: readonly string[];
  readonly semanticEditScriptIds: readonly string[];
  readonly semanticEditProjectionIds: readonly string[];
  readonly semanticEditReplayIds: readonly string[];
  readonly semanticEditReplayStatuses: readonly string[];
  readonly semanticEditReplayActions: readonly string[];
  readonly semanticEditAdmissionStatuses: readonly string[];
  readonly semanticEditAdmissionActions: readonly string[];
  readonly semanticEditAdmissionReadinesses: readonly string[];
  readonly semanticEditReplayCurrentHashes: readonly string[];
  readonly semanticEditReplayOutputHashes: readonly string[];
  readonly sourceBackprojectionModes: readonly string[];
  readonly semanticEditKeys: readonly string[];
  readonly semanticIdentityHashes: readonly string[];
  readonly sourceIdentityHashes: readonly string[];
  readonly operationContentHashes: readonly string[];
  readonly editContentHashes: readonly string[];
  readonly semanticTransformIds: readonly string[];
  readonly semanticTransformKeys: readonly string[];
  readonly semanticTransformIdentityHashes: readonly string[];
  readonly semanticTransformContentHashes: readonly string[];
  readonly projectionIdentityHashes: readonly string[];
  readonly transformBaseHashes: readonly string[];
  readonly transformTargetHashes: readonly string[];
  readonly semanticTransformReadinesses: readonly string[];
  readonly semanticTransformEvidenceIds: readonly string[];
  readonly transformSourceLanguages: readonly string[];
  readonly transformTargetLanguages: readonly string[];
  readonly transformSourcePaths: readonly string[];
  readonly transformTargetPaths: readonly string[];
  readonly transformCrossLanguages: readonly string[];
  readonly transformSourceMapIds: readonly string[];
  readonly transformSourceMapLinkIds: readonly string[];
  readonly transformSourceMapMappingIds: readonly string[];
  readonly targetPortabilityStatuses: readonly string[];
  readonly targetPortabilityActions: readonly string[];
  readonly targetPortabilityReasonCodes: readonly string[];
  readonly patchIds: readonly string[];
  readonly mergeCandidateIds: readonly string[];
  readonly readinesses: readonly string[];
  readonly admissionStatuses: readonly string[];
}

export interface SemanticPatchBundleRecordQueryIndexFilters {
  readonly lineageResolutionId?: string | readonly string[];
  readonly lineageResolutionIds?: readonly string[];
  readonly lineageEventId?: string | readonly string[];
  readonly lineageEventIds?: readonly string[];
  readonly lineageSourcePath?: string | readonly string[];
  readonly lineageSourcePaths?: readonly string[];
  readonly lineageEvidenceId?: string | readonly string[];
  readonly lineageEvidenceIds?: readonly string[];
  readonly lineageProofId?: string | readonly string[];
  readonly lineageProofIds?: readonly string[];
  readonly lineageReasonCode?: string | readonly string[];
  readonly lineageReasonCodes?: readonly string[];
  readonly sourceBackprojectionMode?: string | readonly string[];
  readonly sourceBackprojectionModes?: readonly string[];
  readonly transformBaseHash?: string | readonly string[];
  readonly transformBaseHashes?: readonly string[];
  readonly transformTargetHash?: string | readonly string[];
  readonly transformTargetHashes?: readonly string[];
  readonly transformCrossLanguage?: boolean | string | readonly string[];
  readonly transformCrossLanguages?: readonly string[];
  readonly transformSourceMapId?: string | readonly string[];
  readonly transformSourceMapIds?: readonly string[];
  readonly transformSourceMapLinkId?: string | readonly string[];
  readonly transformSourceMapLinkIds?: readonly string[];
  readonly transformSourceMapMappingId?: string | readonly string[];
  readonly transformSourceMapMappingIds?: readonly string[];
}
