import type{FrontierSourceLanguage,SemanticMergeReadiness}from '@shapeshift-labs/frontier-lang-kernel';
import type { FrontierCompileTarget } from './compile.js';
import type{UniversalConversionAdmissionAction as UCAA,UniversalConversionPriority as UCP,UniversalConversionRouteAction as UCRA,UniversalConversionRouteMode as UCRM,UniversalConversionRisk as UCR,UniversalTranslationAdmissionAction as UTAA,UniversalTranslationAdmissionStatus as UTAS}from './universal-conversion-plan.js';
import type{UniversalConversionArtifactAdmissionBucket as UCAB,UniversalConversionArtifactAdmissionStatus as UCAS}from './universal-conversion-artifacts.js';
import type{UniversalConversionArtifactSourceMapIndex as USMI,UniversalConversionArtifactSourceMapQuery as USMQ}from './universal-conversion-artifact-source-maps.js';
import type{UniversalConversionArtifactRuntimeRouteIndex as URRI,UniversalConversionArtifactRuntimeRouteQuery as URRQ}from './universal-conversion-artifact-runtime-routes.js';
import type{UniversalRepresentationCoverageQuery as URCQ}from './universal-representation-coverage.js';
import type{UniversalInterlinguaQuery as UIQ}from './universal-interlingua.js';
import type{UniversalResourceTransferQuery as URTQ}from './universal-resource-transfer.js';
import type{UniversalLifetimeConstraintQuery as ULCQ}from './universal-lifetime-constraints.js';
import type{UniversalControlFlowConstraintQuery as UCFQ}from './universal-control-flow-constraints.js';
import type{UniversalCallableBoundaryConstraintQuery as UCBCQ}from './universal-callable-boundary-constraints.js';
import type{UniversalAdtPatternConstraintQuery as UAPQ}from './universal-adt-pattern-constraints.js';
import type{UniversalBorrowScopeConstraintQuery as UBSQ}from './universal-borrow-scope-constraints.js';
import type{UniversalBorrowCheckerConstraintQuery as UBCQ}from './universal-borrow-checker-constraints.js';
import type{UniversalDataLayoutConstraintQuery as UDLCQ}from './universal-data-layout-constraints.js';
import type{UniversalLayoutStyleConstraintQuery as ULSCQ}from './universal-layout-style-constraints.js';
import type{UniversalEffectConstraintQuery as UECQ}from './universal-effect-constraints.js';
import type{UniversalConcurrencyModelConstraintQuery as UCMCQ}from './universal-concurrency-model-constraints.js';
import type{UniversalErrorModelConstraintQuery as UEMCQ}from './universal-error-model-constraints.js';
import type{UniversalEvaluationModelConstraintQuery as UEVQ}from './universal-evaluation-model-constraints.js';
import type{UniversalHostEnvironmentConstraintQuery as UHEQ}from './universal-host-environment-constraints.js';
import type{UniversalMemoryModelConstraintQuery as UMMQ}from './universal-memory-model-constraints.js';
import type{UniversalMetaprogrammingConstraintQuery as UMPQ}from './universal-metaprogramming-constraints.js';
import type{UniversalScopeBindingConstraintQuery as USBQ}from './universal-scope-binding-constraints.js';
import type { UniversalModuleConstraintQuery as UMQ } from './universal-module-constraints.js'; import type { UniversalNumericSemanticsConstraintQuery as UNSQ } from './universal-numeric-semantics-constraints.js'; import type { UniversalTextSemanticsConstraintQuery as UTSQ } from './universal-text-semantics-constraints.js'; import type { UniversalCollectionSemanticsConstraintQuery as UCSQ } from './universal-collection-semantics-constraints.js'; import type { UniversalSerializationSemanticsConstraintQuery as USSQ } from './universal-serialization-semantics-constraints.js'; import type { UniversalDependencySemanticsConstraintQuery as UDSQ } from './universal-dependency-semantics-constraints.js';
import type { UniversalObjectModelConstraintQuery as UOMQ } from './universal-object-model-constraints.js';
import type { UniversalProtocolConstraintQuery as UPQ } from './universal-protocol-constraints.js';
import type { UniversalTypeConstraintQuery as UTQ } from './universal-type-constraints.js';
import type{UniversalRuntimeCapabilityKind as URK,UniversalRuntimeProofSignalKind as UPS}from './universal-runtime-capabilities.js'; type RS=readonly string[]; type QS=string|RS; type QR<T>=T|readonly T[];
export type UniversalConversionSemanticEditIndexKey='semanticEditStatuses'|'semanticEditScriptIds'|'semanticEditProjectionIds'|'semanticEditReplayIds'|'semanticEditReplayStatuses'|'semanticEditReplayActions'|'semanticEditAdmissionStatuses'|'semanticEditAdmissionActions'|'semanticEditAdmissionReadinesses'|'semanticEditReplayCurrentHashes'|'semanticEditReplayOutputHashes'|'semanticEditKeys'|'semanticEditHashes'|'semanticIdentityHashes'|'sourceIdentityHashes'|'operationContentHashes'|'editContentHashes'|'sourceBackprojectionModes'|'semanticTransformIds'|'semanticTransformKeys'|'semanticTransformIdentityHashes'|'semanticTransformContentHashes'|'projectionIdentityHashes'|'semanticTransformReadinesses'|'semanticTransformEvidenceIds'|'transformSourceLanguages'|'transformTargetLanguages'|'transformSourcePaths'|'transformTargetPaths'|'transformCrossLanguages'|'transformSourceMapIds'|'transformSourceMapLinkIds'|'transformSourceMapMappingIds'|'transformBaseHashes'|'transformTargetHashes'|'targetPortabilityStatuses'|'targetPortabilityActions'|'targetPortabilityReasonCodes'|'semanticEditSidecarWarningCodes'|'semanticEditSidecarZeroRecordWarningCodes';
export type UniversalConversionSemanticEditMetricKey='semanticEditSidecarQualityRecords'|'semanticEditSidecarSymbolCount'|'semanticEditSidecarOwnershipRegionCount'|'semanticEditSidecarPatchHintCount'|'semanticEditSidecarWarningCount'|'semanticEditSidecarZeroRecordWarningCount';
type USEQK='semanticEditStatus'|'semanticEditStatuses'|'semanticEditScriptId'|'semanticEditScriptIds'|'semanticEditProjectionId'|'semanticEditProjectionIds'|'semanticEditReplayId'|'semanticEditReplayIds'|'semanticEditReplayStatus'|'semanticEditReplayStatuses'|'semanticEditReplayAction'|'semanticEditReplayActions'|'semanticEditAdmission'|'semanticEditAdmissionStatus'|'semanticEditAdmissionStatuses'|'semanticEditAdmissionAction'|'semanticEditAdmissionActions'|'semanticEditAdmissionReadiness'|'semanticEditAdmissionReadinesses'|'semanticEditReplayCurrentHash'|'semanticEditReplayCurrentHashes'|'semanticEditReplayOutputHash'|'semanticEditReplayOutputHashes'|'semanticEditKey'|'semanticEditKeys'|'semanticEditHash'|'semanticEditHashes'|'semanticIdentityHash'|'semanticIdentityHashes'|'sourceIdentityHash'|'sourceIdentityHashes'|'operationContentHash'|'operationContentHashes'|'editContentHash'|'editContentHashes'|'sourceBackprojectionMode'|'sourceBackprojectionModes'|'semanticTransformId'|'semanticTransformIds'|'semanticTransformKey'|'semanticTransformKeys'|'semanticTransformIdentityHash'|'semanticTransformIdentityHashes'|'semanticTransformContentHash'|'semanticTransformContentHashes'|'projectionIdentityHash'|'projectionIdentityHashes'|'semanticTransformReadiness'|'semanticTransformReadinesses'|'semanticTransformEvidenceId'|'semanticTransformEvidenceIds'|'transformSourceLanguage'|'transformSourceLanguages'|'transformTargetLanguage'|'transformTargetLanguages'|'transformSourcePath'|'transformSourcePaths'|'transformTargetPath'|'transformTargetPaths'|'transformCrossLanguage'|'transformCrossLanguages'|'transformSourceMapId'|'transformSourceMapIds'|'transformSourceMapLinkId'|'transformSourceMapLinkIds'|'transformSourceMapMappingId'|'transformSourceMapMappingIds'|'transformBaseHash'|'transformBaseHashes'|'transformTargetHash'|'transformTargetHashes'|'targetPortabilityStatus'|'targetPortabilityStatuses'|'targetPortabilityAction'|'targetPortabilityActions'|'targetPortabilityReasonCode'|'targetPortabilityReasonCodes'|'semanticEditSidecarWarningCode'|'semanticEditSidecarWarningCodes'|'semanticEditSidecarZeroRecordWarningCode'|'semanticEditSidecarZeroRecordWarningCodes';
type UCAIK='routeIds'|'historyIds'|'patchBundleIds'|'admissionRecordIds'|'evidenceReceiptIds'|'languages'|'targets'|'modes'|'lossClasses'|'adapterIds'|'adapterKinds'|'routeMissingEvidence'|'runtimeAdapterRequirementIds'|'runtimeProofObligationIds'|'runtimeProofStatuses'|'blockers'|'reviewReasons'|'readinesses'|'admissionStatuses'|'admissionBuckets'|'admissionRisks'|'sourcePaths'|'sourceHashes'|'ownershipKeys'|'conflictKeys'|'evidenceIds'|'proofIds'|'evidenceReceiptEvidenceIds'|'evidenceReceiptProofEvidenceIds'|'evidenceReceiptMissingEvidence'|'evidenceReceiptRejectedReasons'|'evidenceReceiptRejectedIds';
type UTAIK='translationAdmissionStatuses'|'translationAdmissionActions'|'missingTranslationEvidence'|'translationEvidenceIds'|'translationProofEvidenceIds'|'translationRuntimeReadinesses'|'translationRuntimeAdapterRequirementIds'|'translationRuntimeProofObligationIds'|'translationRuntimeProofCapabilities'|'translationRuntimeProofStatuses'|'translationRuntimeProofRequiredSignals'|'translationRuntimeProofProvidedSignals'|'translationRuntimeProofMissingSignals'|'translationDialectReadinesses'|'translationDialectRecordIds'|'requiredTranslationConstructKinds'|'representedTranslationConstructKinds'|'targetAdapterIds';
type UTDQK='translationRuntimeReadiness'|'translationRuntimeAdapterRequirementId'|'translationRuntimeProofObligationId'|'translationRuntimeProofCapability'|'translationRuntimeProofStatus'|'translationRuntimeProofRequiredSignal'|'translationRuntimeProofProvidedSignal'|'translationRuntimeProofMissingSignal'|'translationDialectReadiness'|'translationDialectRecordId';
type UDK='dialectReadinesses'|'dialectRegistryIds'|'dialectRecordIds'|'dialectConstructKinds'|'dialectExternKinds'|'dialectDispositions'|'dialectEvidenceIds'|'dialectLossIds'; type UDQK='dialectReadiness'|'dialectRegistryId'|'dialectRecordId'|'dialectConstructKind'|'dialectExternKind'|'dialectDisposition'|'dialectEvidenceId'|'dialectLossId';

export interface UniversalConversionArtifactIndex extends USMI, URRI, Readonly<Record<UniversalConversionSemanticEditIndexKey|UCAIK|UTAIK|UDK, RS>>, Readonly<Record<UniversalConversionSemanticEditMetricKey, number>> {
  readonly runtimeProofCapabilities: readonly URK[]; readonly runtimeProofRequiredSignals: readonly UPS[]; readonly runtimeProofProvidedSignals: readonly UPS[]; readonly runtimeProofMissingSignals: readonly UPS[];
  readonly admissionRecordInterlinguaRecordIds: RS; readonly admissionRecordInterlinguaLoweringDispositions: RS;
  readonly admissionRecordInterlinguaConstraintFamilies: RS; readonly admissionRecordInterlinguaConstraintStatuses: RS; readonly admissionRecordInterlinguaConstraintActions: RS; readonly admissionRecordInterlinguaConstraintSourceIds: RS; readonly admissionRecordInterlinguaConstraintEvidenceIds: RS;
  readonly admissionRecordInterlinguaConstraintRequiredKinds: RS; readonly admissionRecordInterlinguaConstraintRepresentedKinds: RS; readonly admissionRecordInterlinguaConstraintMissingKinds: RS; readonly admissionRecordInterlinguaConstraintMissingEvidence: RS; readonly admissionRecordInterlinguaConstraintObligationKinds: RS; readonly admissionRecordInterlinguaConstraintObligationStatuses: RS; readonly admissionRecordInterlinguaConstraintObligationEvidenceIds: RS; readonly admissionRecordInterlinguaConstraintObligationMissingEvidence: RS;
  readonly evidenceReceiptInterlinguaRecordIds: RS; readonly evidenceReceiptInterlinguaLoweringDispositions: RS; readonly evidenceReceiptInterlinguaConstraintFamilies: RS; readonly evidenceReceiptInterlinguaConstraintStatuses: RS; readonly evidenceReceiptInterlinguaConstraintActions: RS; readonly evidenceReceiptInterlinguaConstraintSourceIds: RS; readonly evidenceReceiptInterlinguaConstraintEvidenceIds: RS; readonly evidenceReceiptInterlinguaConstraintRequiredKinds: RS; readonly evidenceReceiptInterlinguaConstraintRepresentedKinds: RS; readonly evidenceReceiptInterlinguaConstraintMissingKinds: RS; readonly evidenceReceiptInterlinguaConstraintMissingEvidence: RS; readonly evidenceReceiptInterlinguaConstraintObligationKinds: RS; readonly evidenceReceiptInterlinguaConstraintObligationStatuses: RS; readonly evidenceReceiptInterlinguaConstraintObligationEvidenceIds: RS; readonly evidenceReceiptInterlinguaConstraintObligationMissingEvidence: RS;
  readonly semanticOperationIds: RS; readonly semanticOperationKinds: RS;
  readonly semanticOperationInterlinguaRecordIds: RS; readonly semanticOperationInterlinguaLoweringDispositions: RS; readonly semanticOperationInterlinguaMissingEvidence: RS; readonly semanticOperationInterlinguaProofEvidenceIds: RS;
  readonly semanticOperationInterlinguaConstraintActions: RS; readonly semanticOperationInterlinguaConstraintSourceIds: RS; readonly semanticOperationInterlinguaConstraintRequiredKinds: RS; readonly semanticOperationInterlinguaConstraintRepresentedKinds: RS;
  readonly representationConstructKinds: RS;
  readonly runtimeCapabilities: RS;
  readonly sourceMapPrecisions: RS;
  readonly resourceTransferStatuses: RS;
  readonly resourceTransferActions: RS;
  readonly resourceTransferMissingEvidence: RS;
  readonly resourceTransferLossKinds: RS;
  readonly ownershipConstraintStatuses: RS;
  readonly ownershipConstraintActions: RS;
  readonly ownershipConstraintMissingEvidence: RS;
  readonly ownershipConstraintMissingKinds: RS;
  readonly lifetimeConstraintStatuses: RS;
  readonly lifetimeConstraintActions: RS;
  readonly lifetimeConstraintMissingEvidence: RS;
  readonly lifetimeConstraintMissingKinds: RS;
  readonly controlFlowConstraintStatuses: RS;
  readonly controlFlowConstraintActions: RS;
  readonly controlFlowConstraintMissingEvidence: RS;
  readonly controlFlowConstraintMissingKinds: RS;
  readonly adtPatternConstraintStatuses: RS; readonly adtPatternConstraintActions: RS;
  readonly adtPatternConstraintMissingEvidence: RS; readonly adtPatternConstraintMissingKinds: RS;
  readonly borrowScopeConstraintStatuses: RS;
  readonly borrowScopeConstraintActions: RS;
  readonly borrowScopeConstraintMissingEvidence: RS;
  readonly borrowScopeConstraintMissingKinds: RS;
  readonly borrowCheckerConstraintStatuses: RS;
  readonly borrowCheckerConstraintActions: RS;
  readonly borrowCheckerConstraintMissingEvidence: RS;
  readonly borrowCheckerConstraintMissingKinds: RS;
  readonly dataLayoutConstraintStatuses: RS;
  readonly dataLayoutConstraintActions: RS;
  readonly dataLayoutConstraintMissingEvidence: RS;
  readonly dataLayoutConstraintMissingKinds: RS;
  readonly layoutStyleConstraintStatuses: RS;
  readonly layoutStyleConstraintActions: RS;
  readonly layoutStyleConstraintMissingEvidence: RS;
  readonly layoutStyleConstraintMissingKinds: RS;
  readonly callableBoundaryConstraintStatuses: RS; readonly callableBoundaryConstraintActions: RS; readonly callableBoundaryConstraintMissingEvidence: RS; readonly callableBoundaryConstraintMissingKinds: RS;
  readonly effectConstraintStatuses: RS;
  readonly effectConstraintActions: RS;
  readonly effectConstraintMissingEvidence: RS;
  readonly effectConstraintMissingKinds: RS;
  readonly concurrencyModelConstraintStatuses: RS;
  readonly concurrencyModelConstraintActions: RS;
  readonly concurrencyModelConstraintMissingEvidence: RS;
  readonly concurrencyModelConstraintMissingKinds: RS;
  readonly errorModelConstraintStatuses: RS;
  readonly errorModelConstraintActions: RS;
  readonly errorModelConstraintMissingEvidence: RS;
  readonly errorModelConstraintMissingKinds: RS;
  readonly evaluationModelConstraintStatuses: RS;
  readonly evaluationModelConstraintActions: RS;
  readonly evaluationModelConstraintMissingEvidence: RS;
  readonly evaluationModelConstraintMissingKinds: RS;
  readonly hostEnvironmentConstraintStatuses: RS; readonly hostEnvironmentConstraintActions: RS; readonly hostEnvironmentConstraintMissingEvidence: RS; readonly hostEnvironmentConstraintMissingKinds: RS;
  readonly memoryModelConstraintStatuses: RS;
  readonly memoryModelConstraintActions: RS;
  readonly memoryModelConstraintMissingEvidence: RS;
  readonly memoryModelConstraintMissingKinds: RS;
  readonly metaprogrammingConstraintStatuses: RS;
  readonly metaprogrammingConstraintActions: RS;
  readonly metaprogrammingConstraintMissingEvidence: RS;
  readonly metaprogrammingConstraintMissingKinds: RS;
  readonly scopeBindingConstraintStatuses: RS; readonly scopeBindingConstraintActions: RS;
  readonly scopeBindingConstraintMissingEvidence: RS; readonly scopeBindingConstraintMissingKinds: RS;
  readonly moduleConstraintStatuses: RS; readonly moduleConstraintActions: RS;
  readonly moduleConstraintMissingEvidence: RS; readonly moduleConstraintMissingKinds: RS;
  readonly numericSemanticsConstraintStatuses: RS; readonly numericSemanticsConstraintActions: RS; readonly numericSemanticsConstraintMissingEvidence: RS; readonly numericSemanticsConstraintMissingKinds: RS; readonly textSemanticsConstraintStatuses: RS; readonly textSemanticsConstraintActions: RS; readonly textSemanticsConstraintMissingEvidence: RS; readonly textSemanticsConstraintMissingKinds: RS; readonly collectionSemanticsConstraintStatuses: RS; readonly collectionSemanticsConstraintActions: RS; readonly collectionSemanticsConstraintMissingEvidence: RS; readonly collectionSemanticsConstraintMissingKinds: RS; readonly serializationSemanticsConstraintStatuses: RS; readonly serializationSemanticsConstraintActions: RS; readonly serializationSemanticsConstraintMissingEvidence: RS; readonly serializationSemanticsConstraintMissingKinds: RS; readonly dependencySemanticsConstraintStatuses: RS; readonly dependencySemanticsConstraintActions: RS; readonly dependencySemanticsConstraintMissingEvidence: RS; readonly dependencySemanticsConstraintMissingKinds: RS;
  readonly objectModelConstraintStatuses: RS; readonly objectModelConstraintActions: RS;
  readonly objectModelConstraintMissingEvidence: RS; readonly objectModelConstraintMissingKinds: RS;
  readonly protocolConstraintStatuses: RS; readonly protocolConstraintActions: RS;
  readonly protocolConstraintMissingEvidence: RS; readonly protocolConstraintMissingKinds: RS;
  readonly typeConstraintStatuses: RS; readonly typeConstraintActions: RS;
  readonly typeConstraintMissingEvidence: RS; readonly typeConstraintMissingKinds: RS;
  readonly interlinguaRecordIds: RS;
  readonly interlinguaLayerKinds: RS;
  readonly interlinguaRepresentedLayerKinds: RS;
  readonly interlinguaMissingLayerKinds: RS;
  readonly interlinguaReviewLayerKinds: RS;
  readonly interlinguaBlockedLayerKinds: RS;
  readonly interlinguaLoweringDispositions: RS;
  readonly interlinguaMissingEvidence: RS;
  readonly interlinguaProofEvidenceIds: RS;
  readonly interlinguaConstraintFamilies: RS;
  readonly interlinguaConstraintStatuses: RS;
  readonly interlinguaConstraintActions: RS;
  readonly interlinguaConstraintRequiredKinds: RS;
  readonly interlinguaConstraintRepresentedKinds: RS;
  readonly interlinguaConstraintMissingKinds: RS;
  readonly interlinguaConstraintMissingEvidence: RS;
  readonly interlinguaConstraintSourceIds: RS; readonly interlinguaConstraintEvidenceIds: RS; readonly interlinguaConstraintObligationKinds: RS; readonly interlinguaConstraintObligationStatuses: RS; readonly interlinguaConstraintObligationEvidenceIds: RS; readonly interlinguaConstraintObligationMissingEvidence: RS;
  readonly transformIdentityHashes: RS;
}

export interface UniversalConversionArtifactQuery extends USMQ, URRQ, URCQ, UIQ, URTQ, ULCQ, UCFQ, UCBCQ, UAPQ, UBSQ, UBCQ, UDLCQ, ULSCQ, UECQ, UCMCQ, UEMCQ, UEVQ, UHEQ, UMMQ, UMPQ, USBQ, UMQ, UNSQ, UTSQ, UCSQ, USSQ, UDSQ, UOMQ, UPQ, UTQ, Readonly<Partial<Record<USEQK, QS|boolean>>>, Readonly<Partial<Record<UTDQK|UDQK, QS>>> {
  readonly routeId?: QS;
  readonly historyId?: QS;
  readonly patchBundleId?: QS;
  readonly admissionRecordId?: QS;
  readonly evidenceReceiptId?: QS;
  readonly sourceLanguage?: FrontierSourceLanguage | QS;
  readonly language?: FrontierSourceLanguage | QS;
  readonly target?: FrontierCompileTarget | QS;
  readonly mode?: UCRM | RS;
  readonly lossClass?: QS;
  readonly adapterId?: QS;
  readonly adapterKind?: QS;
  readonly routeMissingEvidence?: QS; readonly runtimeAdapterRequirementId?: QS;
  readonly runtimeProofObligationId?: QS; readonly runtimeProofCapability?: QR<URK>; readonly runtimeProofStatus?: QS; readonly runtimeProofRequiredSignal?: QR<UPS>; readonly runtimeProofProvidedSignal?: QR<UPS>; readonly runtimeProofMissingSignal?: QR<UPS>;
  readonly blocker?: QS;
  readonly reviewReason?: QS;
  readonly readiness?: SemanticMergeReadiness | QS;
  readonly admissionAction?: UCAA | RS;
  readonly admissionStatus?: UCAS | RS;
  readonly admissionBucket?: UCAB | RS;
  readonly translationAdmissionStatus?: UTAS | RS;
  readonly translationAdmissionAction?: UTAA | RS;
  readonly missingTranslationEvidence?: QS;
  readonly translationEvidenceId?: QS;
  readonly translationProofEvidenceId?: QS;
  readonly requiredTranslationConstructKind?: QS;
  readonly representedTranslationConstructKind?: QS;
  readonly targetAdapterId?: QS;
  readonly risk?: UCR | QS;
  readonly priority?: UCP | RS;
  readonly routeAction?: UCRA | RS;
  readonly sourcePath?: QS;
  readonly sourceHash?: QS;
  readonly ownershipKey?: QS;
  readonly conflictKey?: QS;
  readonly evidenceId?: QS;
  readonly proofId?: QS;
  readonly evidenceReceiptEvidenceId?: QS; readonly evidenceReceiptProofEvidenceId?: QS; readonly evidenceReceiptMissingEvidence?: QS;
  readonly evidenceReceiptRejectedReason?: QS; readonly evidenceReceiptRejectedId?: QS;
  readonly evidenceReceiptInterlinguaRecordId?: QS; readonly evidenceReceiptInterlinguaLoweringDisposition?: QS; readonly evidenceReceiptInterlinguaConstraintFamily?: QS; readonly evidenceReceiptInterlinguaConstraintStatus?: QS; readonly evidenceReceiptInterlinguaConstraintAction?: QS; readonly evidenceReceiptInterlinguaConstraintSourceId?: QS; readonly evidenceReceiptInterlinguaConstraintEvidenceId?: QS; readonly evidenceReceiptInterlinguaConstraintRequiredKind?: QS; readonly evidenceReceiptInterlinguaConstraintRepresentedKind?: QS; readonly evidenceReceiptInterlinguaConstraintMissingKind?: QS; readonly evidenceReceiptInterlinguaConstraintMissingEvidence?: QS; readonly evidenceReceiptInterlinguaConstraintObligationKind?: QS; readonly evidenceReceiptInterlinguaConstraintObligationStatus?: QS; readonly evidenceReceiptInterlinguaConstraintObligationEvidenceId?: QS; readonly evidenceReceiptInterlinguaConstraintObligationMissingEvidence?: QS;
  readonly admissionRecordInterlinguaRecordId?: QS; readonly admissionRecordInterlinguaLoweringDisposition?: QS;
  readonly admissionRecordInterlinguaConstraintFamily?: QS; readonly admissionRecordInterlinguaConstraintStatus?: QS; readonly admissionRecordInterlinguaConstraintAction?: QS; readonly admissionRecordInterlinguaConstraintSourceId?: QS; readonly admissionRecordInterlinguaConstraintEvidenceId?: QS; readonly admissionRecordInterlinguaConstraintRequiredKind?: QS; readonly admissionRecordInterlinguaConstraintRepresentedKind?: QS; readonly admissionRecordInterlinguaConstraintMissingKind?: QS; readonly admissionRecordInterlinguaConstraintMissingEvidence?: QS; readonly admissionRecordInterlinguaConstraintObligationKind?: QS; readonly admissionRecordInterlinguaConstraintObligationStatus?: QS; readonly admissionRecordInterlinguaConstraintObligationEvidenceId?: QS; readonly admissionRecordInterlinguaConstraintObligationMissingEvidence?: QS;
  readonly semanticOperationId?: QS;
  readonly semanticOperationKind?: QS;
  readonly semanticOperationInterlinguaRecordId?: QS;
  readonly semanticOperationInterlinguaLoweringDisposition?: QS;
  readonly semanticOperationInterlinguaMissingEvidence?: QS;
  readonly semanticOperationInterlinguaProofEvidenceId?: QS;
  readonly semanticOperationInterlinguaConstraintAction?: QS; readonly semanticOperationInterlinguaConstraintSourceId?: QS; readonly semanticOperationInterlinguaConstraintRequiredKind?: QS; readonly semanticOperationInterlinguaConstraintRepresentedKind?: QS;
  readonly representationConstructKind?: QS;
  readonly transformIdentityHash?: QS; readonly transformIdentityHashes?: RS;
}
