import type{FrontierSourceLanguage,SemanticMergeReadiness}from '@shapeshift-labs/frontier-lang-kernel';
import type { FrontierCompileTarget } from './compile.js';
import type{UniversalConversionAdmissionAction,UniversalConversionPriority,UniversalConversionRouteAction,UniversalConversionRouteMode,UniversalConversionRisk,UniversalTranslationAdmissionAction,UniversalTranslationAdmissionStatus}from './universal-conversion-plan.js';
import type { UniversalConversionArtifactAdmissionBucket, UniversalConversionArtifactAdmissionStatus } from './universal-conversion-artifacts.js';
import type{UniversalConversionArtifactSourceMapIndex as USMI,UniversalConversionArtifactSourceMapQuery as USMQ}from './universal-conversion-artifact-source-maps.js';
import type{UniversalConversionArtifactRuntimeRouteIndex as URRI,UniversalConversionArtifactRuntimeRouteQuery as URRQ}from './universal-conversion-artifact-runtime-routes.js';
import type{UniversalRepresentationCoverageQuery}from './universal-representation-coverage.js';
import type{UniversalInterlinguaQuery}from './universal-interlingua.js';
import type{UniversalResourceTransferQuery}from './universal-resource-transfer.js';
import type{UniversalLifetimeConstraintQuery}from './universal-lifetime-constraints.js';
import type{UniversalControlFlowConstraintQuery}from './universal-control-flow-constraints.js';
import type{UniversalCallableBoundaryConstraintQuery}from './universal-callable-boundary-constraints.js';
import type{UniversalAdtPatternConstraintQuery}from './universal-adt-pattern-constraints.js';
import type{UniversalBorrowScopeConstraintQuery}from './universal-borrow-scope-constraints.js';
import type{UniversalBorrowCheckerConstraintQuery}from './universal-borrow-checker-constraints.js';
import type{UniversalDataLayoutConstraintQuery}from './universal-data-layout-constraints.js';
import type{UniversalEffectConstraintQuery}from './universal-effect-constraints.js';
import type{UniversalConcurrencyModelConstraintQuery}from './universal-concurrency-model-constraints.js';
import type{UniversalErrorModelConstraintQuery}from './universal-error-model-constraints.js';
import type{UniversalEvaluationModelConstraintQuery}from './universal-evaluation-model-constraints.js';
import type{UniversalHostEnvironmentConstraintQuery}from './universal-host-environment-constraints.js';
import type{UniversalMemoryModelConstraintQuery}from './universal-memory-model-constraints.js';
import type{UniversalMetaprogrammingConstraintQuery}from './universal-metaprogramming-constraints.js';
import type{UniversalScopeBindingConstraintQuery}from './universal-scope-binding-constraints.js';
import type { UniversalModuleConstraintQuery } from './universal-module-constraints.js'; import type { UniversalNumericSemanticsConstraintQuery } from './universal-numeric-semantics-constraints.js'; import type { UniversalTextSemanticsConstraintQuery } from './universal-text-semantics-constraints.js'; import type { UniversalCollectionSemanticsConstraintQuery } from './universal-collection-semantics-constraints.js'; import type { UniversalSerializationSemanticsConstraintQuery } from './universal-serialization-semantics-constraints.js'; import type { UniversalDependencySemanticsConstraintQuery } from './universal-dependency-semantics-constraints.js';
import type { UniversalObjectModelConstraintQuery } from './universal-object-model-constraints.js';
import type { UniversalProtocolConstraintQuery } from './universal-protocol-constraints.js';
import type { UniversalTypeConstraintQuery } from './universal-type-constraints.js';
import type { UniversalRuntimeCapabilityKind as URK, UniversalRuntimeProofSignalKind as UPS } from './universal-runtime-capabilities.js'; type RS=readonly string[]; type QS=string|RS;
export type UniversalConversionSemanticEditIndexKey='semanticEditStatuses'|'semanticEditScriptIds'|'semanticEditProjectionIds'|'semanticEditReplayIds'|'semanticEditReplayStatuses'|'semanticEditReplayActions'|'semanticEditAdmissionStatuses'|'semanticEditAdmissionActions'|'semanticEditAdmissionReadinesses'|'semanticEditReplayCurrentHashes'|'semanticEditReplayOutputHashes'|'semanticEditKeys'|'semanticEditHashes'|'semanticIdentityHashes'|'sourceIdentityHashes'|'operationContentHashes'|'editContentHashes'|'sourceBackprojectionModes'|'semanticTransformIds'|'semanticTransformKeys'|'semanticTransformIdentityHashes'|'semanticTransformContentHashes'|'projectionIdentityHashes'|'semanticTransformReadinesses'|'semanticTransformEvidenceIds'|'transformSourceLanguages'|'transformTargetLanguages'|'transformSourcePaths'|'transformTargetPaths'|'transformCrossLanguages'|'transformSourceMapIds'|'transformSourceMapLinkIds'|'transformSourceMapMappingIds'|'transformBaseHashes'|'transformTargetHashes'|'targetPortabilityStatuses'|'targetPortabilityActions'|'targetPortabilityReasonCodes';
type USEQK='semanticEditStatus'|'semanticEditStatuses'|'semanticEditScriptId'|'semanticEditScriptIds'|'semanticEditProjectionId'|'semanticEditProjectionIds'|'semanticEditReplayId'|'semanticEditReplayIds'|'semanticEditReplayStatus'|'semanticEditReplayStatuses'|'semanticEditReplayAction'|'semanticEditReplayActions'|'semanticEditAdmission'|'semanticEditAdmissionStatus'|'semanticEditAdmissionStatuses'|'semanticEditAdmissionAction'|'semanticEditAdmissionActions'|'semanticEditAdmissionReadiness'|'semanticEditAdmissionReadinesses'|'semanticEditReplayCurrentHash'|'semanticEditReplayCurrentHashes'|'semanticEditReplayOutputHash'|'semanticEditReplayOutputHashes'|'semanticEditKey'|'semanticEditKeys'|'semanticEditHash'|'semanticEditHashes'|'semanticIdentityHash'|'semanticIdentityHashes'|'sourceIdentityHash'|'sourceIdentityHashes'|'operationContentHash'|'operationContentHashes'|'editContentHash'|'editContentHashes'|'sourceBackprojectionMode'|'sourceBackprojectionModes'|'semanticTransformId'|'semanticTransformIds'|'semanticTransformKey'|'semanticTransformKeys'|'semanticTransformIdentityHash'|'semanticTransformIdentityHashes'|'semanticTransformContentHash'|'semanticTransformContentHashes'|'projectionIdentityHash'|'projectionIdentityHashes'|'semanticTransformReadiness'|'semanticTransformReadinesses'|'semanticTransformEvidenceId'|'semanticTransformEvidenceIds'|'transformSourceLanguage'|'transformSourceLanguages'|'transformTargetLanguage'|'transformTargetLanguages'|'transformSourcePath'|'transformSourcePaths'|'transformTargetPath'|'transformTargetPaths'|'transformCrossLanguage'|'transformCrossLanguages'|'transformSourceMapId'|'transformSourceMapIds'|'transformSourceMapLinkId'|'transformSourceMapLinkIds'|'transformSourceMapMappingId'|'transformSourceMapMappingIds'|'transformBaseHash'|'transformBaseHashes'|'transformTargetHash'|'transformTargetHashes'|'targetPortabilityStatus'|'targetPortabilityStatuses'|'targetPortabilityAction'|'targetPortabilityActions'|'targetPortabilityReasonCode'|'targetPortabilityReasonCodes';

export interface UniversalConversionArtifactIndex extends USMI, URRI, Readonly<Record<UniversalConversionSemanticEditIndexKey, RS>> {
  readonly routeIds: RS;
  readonly historyIds: RS;
  readonly patchBundleIds: RS;
  readonly admissionRecordIds: RS;
  readonly evidenceReceiptIds: RS;
  readonly languages: RS;
  readonly targets: RS;
  readonly modes: RS;
  readonly lossClasses: RS;
  readonly adapterIds: RS;
  readonly adapterKinds: RS;
  readonly routeMissingEvidence: RS; readonly runtimeAdapterRequirementIds: RS;
  readonly runtimeProofObligationIds: RS; readonly runtimeProofCapabilities: readonly URK[]; readonly runtimeProofStatuses: RS; readonly runtimeProofRequiredSignals: readonly UPS[]; readonly runtimeProofProvidedSignals: readonly UPS[]; readonly runtimeProofMissingSignals: readonly UPS[];
  readonly blockers: RS; readonly reviewReasons: RS;
  readonly readinesses: RS;
  readonly admissionStatuses: RS;
  readonly admissionBuckets: RS;
  readonly admissionRisks: RS;
  readonly admissionRecordInterlinguaRecordIds: RS; readonly admissionRecordInterlinguaLoweringDispositions: RS;
  readonly admissionRecordInterlinguaConstraintFamilies: RS; readonly admissionRecordInterlinguaConstraintStatuses: RS; readonly admissionRecordInterlinguaConstraintActions: RS; readonly admissionRecordInterlinguaConstraintSourceIds: RS; readonly admissionRecordInterlinguaConstraintEvidenceIds: RS;
  readonly admissionRecordInterlinguaConstraintRequiredKinds: RS; readonly admissionRecordInterlinguaConstraintRepresentedKinds: RS; readonly admissionRecordInterlinguaConstraintMissingKinds: RS; readonly admissionRecordInterlinguaConstraintMissingEvidence: RS; readonly admissionRecordInterlinguaConstraintObligationKinds: RS; readonly admissionRecordInterlinguaConstraintObligationStatuses: RS; readonly admissionRecordInterlinguaConstraintObligationEvidenceIds: RS; readonly admissionRecordInterlinguaConstraintObligationMissingEvidence: RS;
  readonly sourcePaths: RS;
  readonly sourceHashes: RS;
  readonly ownershipKeys: RS;
  readonly conflictKeys: RS;
  readonly evidenceIds: RS;
  readonly proofIds: RS;
  readonly evidenceReceiptEvidenceIds: RS; readonly evidenceReceiptProofEvidenceIds: RS; readonly evidenceReceiptMissingEvidence: RS;
  readonly evidenceReceiptRejectedReasons: RS; readonly evidenceReceiptRejectedIds: RS;
  readonly evidenceReceiptInterlinguaRecordIds: RS; readonly evidenceReceiptInterlinguaLoweringDispositions: RS; readonly evidenceReceiptInterlinguaConstraintFamilies: RS; readonly evidenceReceiptInterlinguaConstraintStatuses: RS; readonly evidenceReceiptInterlinguaConstraintActions: RS; readonly evidenceReceiptInterlinguaConstraintSourceIds: RS; readonly evidenceReceiptInterlinguaConstraintEvidenceIds: RS; readonly evidenceReceiptInterlinguaConstraintRequiredKinds: RS; readonly evidenceReceiptInterlinguaConstraintRepresentedKinds: RS; readonly evidenceReceiptInterlinguaConstraintMissingKinds: RS; readonly evidenceReceiptInterlinguaConstraintMissingEvidence: RS; readonly evidenceReceiptInterlinguaConstraintObligationKinds: RS; readonly evidenceReceiptInterlinguaConstraintObligationStatuses: RS; readonly evidenceReceiptInterlinguaConstraintObligationEvidenceIds: RS; readonly evidenceReceiptInterlinguaConstraintObligationMissingEvidence: RS;
  readonly semanticOperationIds: RS; readonly semanticOperationKinds: RS;
  readonly semanticOperationInterlinguaRecordIds: RS; readonly semanticOperationInterlinguaLoweringDispositions: RS; readonly semanticOperationInterlinguaMissingEvidence: RS; readonly semanticOperationInterlinguaProofEvidenceIds: RS;
  readonly semanticOperationInterlinguaConstraintActions: RS; readonly semanticOperationInterlinguaConstraintSourceIds: RS; readonly semanticOperationInterlinguaConstraintRequiredKinds: RS; readonly semanticOperationInterlinguaConstraintRepresentedKinds: RS;
  readonly representationConstructKinds: RS;
  readonly runtimeCapabilities: RS;
  readonly sourceMapPrecisions: RS;
  readonly translationAdmissionStatuses: RS;
  readonly translationAdmissionActions: RS;
  readonly missingTranslationEvidence: RS;
  readonly translationEvidenceIds: RS;
  readonly translationProofEvidenceIds: RS;
  readonly requiredTranslationConstructKinds: RS;
  readonly representedTranslationConstructKinds: RS;
  readonly targetAdapterIds: RS;
  readonly resourceTransferStatuses: RS;
  readonly resourceTransferActions: RS;
  readonly resourceTransferMissingEvidence: RS;
  readonly resourceTransferLossKinds: RS;
  readonly ownershipConstraintStatuses: RS;
  readonly ownershipConstraintActions: RS;
  readonly ownershipConstraintMissingEvidence: RS;
  readonly ownershipConstraintMissingKinds: RS;
  readonly lifetimeConstraintStatuses: RS;
  readonly lifetimeConstraintActions: RS;
  readonly lifetimeConstraintMissingEvidence: RS;
  readonly lifetimeConstraintMissingKinds: RS;
  readonly controlFlowConstraintStatuses: RS;
  readonly controlFlowConstraintActions: RS;
  readonly controlFlowConstraintMissingEvidence: RS;
  readonly controlFlowConstraintMissingKinds: RS;
  readonly adtPatternConstraintStatuses: RS; readonly adtPatternConstraintActions: RS;
  readonly adtPatternConstraintMissingEvidence: RS; readonly adtPatternConstraintMissingKinds: RS;
  readonly borrowScopeConstraintStatuses: RS;
  readonly borrowScopeConstraintActions: RS;
  readonly borrowScopeConstraintMissingEvidence: RS;
  readonly borrowScopeConstraintMissingKinds: RS;
  readonly borrowCheckerConstraintStatuses: RS;
  readonly borrowCheckerConstraintActions: RS;
  readonly borrowCheckerConstraintMissingEvidence: RS;
  readonly borrowCheckerConstraintMissingKinds: RS;
  readonly dataLayoutConstraintStatuses: RS;
  readonly dataLayoutConstraintActions: RS;
  readonly dataLayoutConstraintMissingEvidence: RS;
  readonly dataLayoutConstraintMissingKinds: RS;
  readonly callableBoundaryConstraintStatuses: RS; readonly callableBoundaryConstraintActions: RS; readonly callableBoundaryConstraintMissingEvidence: RS; readonly callableBoundaryConstraintMissingKinds: RS;
  readonly effectConstraintStatuses: RS;
  readonly effectConstraintActions: RS;
  readonly effectConstraintMissingEvidence: RS;
  readonly effectConstraintMissingKinds: RS;
  readonly concurrencyModelConstraintStatuses: RS;
  readonly concurrencyModelConstraintActions: RS;
  readonly concurrencyModelConstraintMissingEvidence: RS;
  readonly concurrencyModelConstraintMissingKinds: RS;
  readonly errorModelConstraintStatuses: RS;
  readonly errorModelConstraintActions: RS;
  readonly errorModelConstraintMissingEvidence: RS;
  readonly errorModelConstraintMissingKinds: RS;
  readonly evaluationModelConstraintStatuses: RS;
  readonly evaluationModelConstraintActions: RS;
  readonly evaluationModelConstraintMissingEvidence: RS;
  readonly evaluationModelConstraintMissingKinds: RS;
  readonly hostEnvironmentConstraintStatuses: RS; readonly hostEnvironmentConstraintActions: RS; readonly hostEnvironmentConstraintMissingEvidence: RS; readonly hostEnvironmentConstraintMissingKinds: RS;
  readonly memoryModelConstraintStatuses: RS;
  readonly memoryModelConstraintActions: RS;
  readonly memoryModelConstraintMissingEvidence: RS;
  readonly memoryModelConstraintMissingKinds: RS;
  readonly metaprogrammingConstraintStatuses: RS;
  readonly metaprogrammingConstraintActions: RS;
  readonly metaprogrammingConstraintMissingEvidence: RS;
  readonly metaprogrammingConstraintMissingKinds: RS;
  readonly scopeBindingConstraintStatuses: RS; readonly scopeBindingConstraintActions: RS;
  readonly scopeBindingConstraintMissingEvidence: RS; readonly scopeBindingConstraintMissingKinds: RS;
  readonly moduleConstraintStatuses: RS; readonly moduleConstraintActions: RS;
  readonly moduleConstraintMissingEvidence: RS; readonly moduleConstraintMissingKinds: RS;
  readonly numericSemanticsConstraintStatuses: RS; readonly numericSemanticsConstraintActions: RS; readonly numericSemanticsConstraintMissingEvidence: RS; readonly numericSemanticsConstraintMissingKinds: RS; readonly textSemanticsConstraintStatuses: RS; readonly textSemanticsConstraintActions: RS; readonly textSemanticsConstraintMissingEvidence: RS; readonly textSemanticsConstraintMissingKinds: RS; readonly collectionSemanticsConstraintStatuses: RS; readonly collectionSemanticsConstraintActions: RS; readonly collectionSemanticsConstraintMissingEvidence: RS; readonly collectionSemanticsConstraintMissingKinds: RS; readonly serializationSemanticsConstraintStatuses: RS; readonly serializationSemanticsConstraintActions: RS; readonly serializationSemanticsConstraintMissingEvidence: RS; readonly serializationSemanticsConstraintMissingKinds: RS; readonly dependencySemanticsConstraintStatuses: RS; readonly dependencySemanticsConstraintActions: RS; readonly dependencySemanticsConstraintMissingEvidence: RS; readonly dependencySemanticsConstraintMissingKinds: RS;
  readonly objectModelConstraintStatuses: RS; readonly objectModelConstraintActions: RS;
  readonly objectModelConstraintMissingEvidence: RS; readonly objectModelConstraintMissingKinds: RS;
  readonly protocolConstraintStatuses: RS; readonly protocolConstraintActions: RS;
  readonly protocolConstraintMissingEvidence: RS; readonly protocolConstraintMissingKinds: RS;
  readonly typeConstraintStatuses: RS; readonly typeConstraintActions: RS;
  readonly typeConstraintMissingEvidence: RS; readonly typeConstraintMissingKinds: RS;
  readonly interlinguaRecordIds: RS;
  readonly interlinguaLayerKinds: RS;
  readonly interlinguaRepresentedLayerKinds: RS;
  readonly interlinguaMissingLayerKinds: RS;
  readonly interlinguaReviewLayerKinds: RS;
  readonly interlinguaBlockedLayerKinds: RS;
  readonly interlinguaLoweringDispositions: RS;
  readonly interlinguaMissingEvidence: RS;
  readonly interlinguaProofEvidenceIds: RS;
  readonly interlinguaConstraintFamilies: RS;
  readonly interlinguaConstraintStatuses: RS;
  readonly interlinguaConstraintActions: RS;
  readonly interlinguaConstraintRequiredKinds: RS;
  readonly interlinguaConstraintRepresentedKinds: RS;
  readonly interlinguaConstraintMissingKinds: RS;
  readonly interlinguaConstraintMissingEvidence: RS;
  readonly interlinguaConstraintSourceIds: RS; readonly interlinguaConstraintEvidenceIds: RS; readonly interlinguaConstraintObligationKinds: RS; readonly interlinguaConstraintObligationStatuses: RS; readonly interlinguaConstraintObligationEvidenceIds: RS; readonly interlinguaConstraintObligationMissingEvidence: RS;
  readonly transformIdentityHashes: RS;
}

export interface UniversalConversionArtifactQuery extends USMQ, URRQ, UniversalRepresentationCoverageQuery, UniversalInterlinguaQuery, UniversalResourceTransferQuery, UniversalLifetimeConstraintQuery, UniversalControlFlowConstraintQuery, UniversalCallableBoundaryConstraintQuery, UniversalAdtPatternConstraintQuery, UniversalBorrowScopeConstraintQuery, UniversalBorrowCheckerConstraintQuery, UniversalDataLayoutConstraintQuery, UniversalEffectConstraintQuery, UniversalConcurrencyModelConstraintQuery, UniversalErrorModelConstraintQuery, UniversalEvaluationModelConstraintQuery, UniversalHostEnvironmentConstraintQuery, UniversalMemoryModelConstraintQuery, UniversalMetaprogrammingConstraintQuery, UniversalScopeBindingConstraintQuery, UniversalModuleConstraintQuery, UniversalNumericSemanticsConstraintQuery, UniversalTextSemanticsConstraintQuery, UniversalCollectionSemanticsConstraintQuery, UniversalSerializationSemanticsConstraintQuery, UniversalDependencySemanticsConstraintQuery, UniversalObjectModelConstraintQuery, UniversalProtocolConstraintQuery, UniversalTypeConstraintQuery, Readonly<Partial<Record<USEQK, QS|boolean>>> {
  readonly routeId?: QS;
  readonly historyId?: QS;
  readonly patchBundleId?: QS;
  readonly admissionRecordId?: QS;
  readonly evidenceReceiptId?: QS;
  readonly sourceLanguage?: FrontierSourceLanguage | QS;
  readonly target?: FrontierCompileTarget | QS;
  readonly mode?: UniversalConversionRouteMode | RS;
  readonly lossClass?: QS;
  readonly adapterId?: QS;
  readonly adapterKind?: QS;
  readonly routeMissingEvidence?: QS; readonly runtimeAdapterRequirementId?: QS;
  readonly runtimeProofObligationId?: QS; readonly runtimeProofCapability?: URK | readonly URK[]; readonly runtimeProofStatus?: QS; readonly runtimeProofRequiredSignal?: UPS | readonly UPS[]; readonly runtimeProofProvidedSignal?: UPS | readonly UPS[]; readonly runtimeProofMissingSignal?: UPS | readonly UPS[];
  readonly blocker?: QS;
  readonly reviewReason?: QS;
  readonly readiness?: SemanticMergeReadiness | QS;
  readonly admissionAction?: UniversalConversionAdmissionAction | RS;
  readonly admissionStatus?: UniversalConversionArtifactAdmissionStatus | RS;
  readonly admissionBucket?: UniversalConversionArtifactAdmissionBucket | RS;
  readonly translationAdmissionStatus?: UniversalTranslationAdmissionStatus | RS;
  readonly translationAdmissionAction?: UniversalTranslationAdmissionAction | RS;
  readonly missingTranslationEvidence?: QS;
  readonly translationEvidenceId?: QS;
  readonly translationProofEvidenceId?: QS;
  readonly requiredTranslationConstructKind?: QS;
  readonly representedTranslationConstructKind?: QS;
  readonly targetAdapterId?: QS;
  readonly risk?: UniversalConversionRisk | QS;
  readonly priority?: UniversalConversionPriority | RS;
  readonly routeAction?: UniversalConversionRouteAction | RS;
  readonly sourcePath?: QS;
  readonly sourceHash?: QS;
  readonly ownershipKey?: QS;
  readonly conflictKey?: QS;
  readonly evidenceId?: QS;
  readonly proofId?: QS;
  readonly evidenceReceiptEvidenceId?: QS; readonly evidenceReceiptProofEvidenceId?: QS; readonly evidenceReceiptMissingEvidence?: QS;
  readonly evidenceReceiptRejectedReason?: QS; readonly evidenceReceiptRejectedId?: QS;
  readonly evidenceReceiptInterlinguaRecordId?: QS; readonly evidenceReceiptInterlinguaLoweringDisposition?: QS; readonly evidenceReceiptInterlinguaConstraintFamily?: QS; readonly evidenceReceiptInterlinguaConstraintStatus?: QS; readonly evidenceReceiptInterlinguaConstraintAction?: QS; readonly evidenceReceiptInterlinguaConstraintSourceId?: QS; readonly evidenceReceiptInterlinguaConstraintEvidenceId?: QS; readonly evidenceReceiptInterlinguaConstraintRequiredKind?: QS; readonly evidenceReceiptInterlinguaConstraintRepresentedKind?: QS; readonly evidenceReceiptInterlinguaConstraintMissingKind?: QS; readonly evidenceReceiptInterlinguaConstraintMissingEvidence?: QS; readonly evidenceReceiptInterlinguaConstraintObligationKind?: QS; readonly evidenceReceiptInterlinguaConstraintObligationStatus?: QS; readonly evidenceReceiptInterlinguaConstraintObligationEvidenceId?: QS; readonly evidenceReceiptInterlinguaConstraintObligationMissingEvidence?: QS;
  readonly admissionRecordInterlinguaRecordId?: QS; readonly admissionRecordInterlinguaLoweringDisposition?: QS;
  readonly admissionRecordInterlinguaConstraintFamily?: QS; readonly admissionRecordInterlinguaConstraintStatus?: QS; readonly admissionRecordInterlinguaConstraintAction?: QS; readonly admissionRecordInterlinguaConstraintSourceId?: QS; readonly admissionRecordInterlinguaConstraintEvidenceId?: QS; readonly admissionRecordInterlinguaConstraintRequiredKind?: QS; readonly admissionRecordInterlinguaConstraintRepresentedKind?: QS; readonly admissionRecordInterlinguaConstraintMissingKind?: QS; readonly admissionRecordInterlinguaConstraintMissingEvidence?: QS; readonly admissionRecordInterlinguaConstraintObligationKind?: QS; readonly admissionRecordInterlinguaConstraintObligationStatus?: QS; readonly admissionRecordInterlinguaConstraintObligationEvidenceId?: QS; readonly admissionRecordInterlinguaConstraintObligationMissingEvidence?: QS;
  readonly semanticOperationId?: QS;
  readonly semanticOperationKind?: QS;
  readonly semanticOperationInterlinguaRecordId?: QS;
  readonly semanticOperationInterlinguaLoweringDisposition?: QS;
  readonly semanticOperationInterlinguaMissingEvidence?: QS;
  readonly semanticOperationInterlinguaProofEvidenceId?: QS;
  readonly semanticOperationInterlinguaConstraintAction?: QS; readonly semanticOperationInterlinguaConstraintSourceId?: QS; readonly semanticOperationInterlinguaConstraintRequiredKind?: QS; readonly semanticOperationInterlinguaConstraintRepresentedKind?: QS;
  readonly representationConstructKind?: QS;
  readonly transformIdentityHash?: QS; readonly transformIdentityHashes?: RS;
}
