import type { UniversalResourceTransferEvidence as ResEv, UniversalResourceTransferInput as ResIn, UniversalResourceTransferQuery as ResQ } from './universal-resource-transfer.js';
import type { UniversalLifetimeConstraintEvidence as LtEv, UniversalLifetimeConstraintInput as LtIn, UniversalLifetimeConstraintQuery as LtQ } from './universal-lifetime-constraints.js'; import type { UniversalControlFlowConstraintEvidence as CfEv, UniversalControlFlowConstraintInput as CfIn, UniversalControlFlowConstraintQuery as CfQ } from './universal-control-flow-constraints.js'; import type { UniversalCallableBoundaryConstraintEvidence as CbEv, UniversalCallableBoundaryConstraintInput as CbIn, UniversalCallableBoundaryConstraintQuery as CbQ } from './universal-callable-boundary-constraints.js'; import type { UniversalAdtPatternConstraintEvidence as AdtEv, UniversalAdtPatternConstraintInput as AdtIn, UniversalAdtPatternConstraintQuery as AdtQ } from './universal-adt-pattern-constraints.js'; import type { UniversalBorrowScopeConstraintEvidence as BsEv, UniversalBorrowScopeConstraintInput as BsIn, UniversalBorrowScopeConstraintQuery as BsQ } from './universal-borrow-scope-constraints.js'; import type { UniversalBorrowCheckerConstraintEvidence as BcEv, UniversalBorrowCheckerConstraintInput as BcIn, UniversalBorrowCheckerConstraintQuery as BcQ } from './universal-borrow-checker-constraints.js';
import type { UniversalDataLayoutConstraintEvidence as DlEv, UniversalDataLayoutConstraintInput as DlIn, UniversalDataLayoutConstraintQuery as DlQ } from './universal-data-layout-constraints.js'; import type { UniversalEffectConstraintEvidence as EfEv, UniversalEffectConstraintInput as EfIn, UniversalEffectConstraintQuery as EfQ } from './universal-effect-constraints.js'; import type { UniversalConcurrencyModelConstraintEvidence as ConEv, UniversalConcurrencyModelConstraintInput as ConIn, UniversalConcurrencyModelConstraintQuery as ConQ } from './universal-concurrency-model-constraints.js'; import type { UniversalErrorModelConstraintEvidence as ErrEv, UniversalErrorModelConstraintInput as ErrIn, UniversalErrorModelConstraintQuery as ErrQ } from './universal-error-model-constraints.js'; import type { UniversalEvaluationModelConstraintEvidence as EvalEv, UniversalEvaluationModelConstraintInput as EvalIn, UniversalEvaluationModelConstraintQuery as EvalQ } from './universal-evaluation-model-constraints.js';
import type { UniversalHostEnvironmentConstraintEvidence as HostEv, UniversalHostEnvironmentConstraintInput as HostIn, UniversalHostEnvironmentConstraintQuery as HostQ } from './universal-host-environment-constraints.js'; import type { UniversalMemoryModelConstraintEvidence as MemEv, UniversalMemoryModelConstraintInput as MemIn, UniversalMemoryModelConstraintQuery as MemQ } from './universal-memory-model-constraints.js'; import type { UniversalMetaprogrammingConstraintEvidence as MetaEv, UniversalMetaprogrammingConstraintInput as MetaIn, UniversalMetaprogrammingConstraintQuery as MetaQ } from './universal-metaprogramming-constraints.js'; import type { UniversalScopeBindingConstraintEvidence as SbEv, UniversalScopeBindingConstraintInput as SbIn, UniversalScopeBindingConstraintQuery as SbQ } from './universal-scope-binding-constraints.js';
import type { UniversalModuleConstraintEvidence as ModEv, UniversalModuleConstraintInput as ModIn, UniversalModuleConstraintQuery as ModQ } from './universal-module-constraints.js'; import type { UniversalNumericSemanticsConstraintEvidence as NumEv, UniversalNumericSemanticsConstraintInput as NumIn, UniversalNumericSemanticsConstraintQuery as NumQ } from './universal-numeric-semantics-constraints.js'; import type { UniversalTextSemanticsConstraintEvidence as TxtEv, UniversalTextSemanticsConstraintInput as TxtIn, UniversalTextSemanticsConstraintQuery as TxtQ } from './universal-text-semantics-constraints.js'; import type { UniversalCollectionSemanticsConstraintEvidence as ColEv, UniversalCollectionSemanticsConstraintInput as ColIn, UniversalCollectionSemanticsConstraintQuery as ColQ } from './universal-collection-semantics-constraints.js'; import type { UniversalSerializationSemanticsConstraintEvidence as SerEv, UniversalSerializationSemanticsConstraintInput as SerIn, UniversalSerializationSemanticsConstraintQuery as SerQ } from './universal-serialization-semantics-constraints.js'; import type { UniversalDependencySemanticsConstraintEvidence as DepEv, UniversalDependencySemanticsConstraintInput as DepIn, UniversalDependencySemanticsConstraintQuery as DepQ } from './universal-dependency-semantics-constraints.js';
import type { UniversalObjectModelConstraintEvidence as ObjEv, UniversalObjectModelConstraintInput as ObjIn, UniversalObjectModelConstraintQuery as ObjQ } from './universal-object-model-constraints.js'; import type { UniversalProtocolConstraintEvidence as ProtoEv, UniversalProtocolConstraintInput as ProtoIn, UniversalProtocolConstraintQuery as ProtoQ } from './universal-protocol-constraints.js'; import type { UniversalTypeConstraintEvidence as TyEv, UniversalTypeConstraintInput as TyIn, UniversalTypeConstraintQuery as TyQ } from './universal-type-constraints.js';

export interface UniversalConversionRouteConstraintFields {
  readonly resourceTransfer?: ResEv; readonly lifetimeConstraint?: LtEv; readonly controlFlowConstraint?: CfEv; readonly callableBoundaryConstraint?: CbEv; readonly adtPatternConstraint?: AdtEv; readonly borrowScopeConstraint?: BsEv; readonly borrowCheckerConstraint?: BcEv; readonly dataLayoutConstraint?: DlEv; readonly effectConstraint?: EfEv; readonly concurrencyModelConstraint?: ConEv; readonly errorModelConstraint?: ErrEv; readonly evaluationModelConstraint?: EvalEv; readonly hostEnvironmentConstraint?: HostEv; readonly memoryModelConstraint?: MemEv; readonly metaprogrammingConstraint?: MetaEv; readonly scopeBindingConstraint?: SbEv; readonly moduleConstraint?: ModEv; readonly numericSemanticsConstraint?: NumEv; readonly textSemanticsConstraint?: TxtEv; readonly collectionSemanticsConstraint?: ColEv; readonly serializationSemanticsConstraint?: SerEv; readonly dependencySemanticsConstraint?: DepEv; readonly objectModelConstraint?: ObjEv; readonly protocolConstraint?: ProtoEv; readonly typeConstraint?: TyEv;
}

export interface UniversalConversionPlanConstraintOptions {
  readonly resourceTransfer?: ResIn | ResEv; readonly translationResourceTransfer?: ResIn | ResEv; readonly resourceTransfers?: readonly (ResIn | ResEv)[];
  readonly lifetimeConstraint?: LtIn | LtEv; readonly translationLifetimeConstraint?: LtIn | LtEv; readonly lifetimeConstraints?: readonly (LtIn | LtEv)[]; readonly controlFlowConstraint?: CfIn | CfEv; readonly translationControlFlowConstraint?: CfIn | CfEv; readonly controlFlowConstraints?: readonly (CfIn | CfEv)[]; readonly callableBoundaryConstraint?: CbIn | CbEv; readonly translationCallableBoundaryConstraint?: CbIn | CbEv; readonly callableBoundaryConstraints?: readonly (CbIn | CbEv)[]; readonly adtPatternConstraint?: AdtIn | AdtEv; readonly translationAdtPatternConstraint?: AdtIn | AdtEv; readonly adtPatternConstraints?: readonly (AdtIn | AdtEv)[]; readonly borrowScopeConstraint?: BsIn | BsEv; readonly translationBorrowScopeConstraint?: BsIn | BsEv; readonly borrowScopeConstraints?: readonly (BsIn | BsEv)[]; readonly borrowCheckerConstraint?: BcIn | BcEv; readonly translationBorrowCheckerConstraint?: BcIn | BcEv; readonly borrowCheckerConstraints?: readonly (BcIn | BcEv)[];
  readonly dataLayoutConstraint?: DlIn | DlEv; readonly translationDataLayoutConstraint?: DlIn | DlEv; readonly dataLayoutConstraints?: readonly (DlIn | DlEv)[]; readonly effectConstraint?: EfIn | EfEv; readonly translationEffectConstraint?: EfIn | EfEv; readonly effectConstraints?: readonly (EfIn | EfEv)[]; readonly concurrencyModelConstraint?: ConIn | ConEv; readonly translationConcurrencyModelConstraint?: ConIn | ConEv; readonly concurrencyModelConstraints?: readonly (ConIn | ConEv)[]; readonly errorModelConstraint?: ErrIn | ErrEv; readonly translationErrorModelConstraint?: ErrIn | ErrEv; readonly errorModelConstraints?: readonly (ErrIn | ErrEv)[]; readonly evaluationModelConstraint?: EvalIn | EvalEv; readonly translationEvaluationModelConstraint?: EvalIn | EvalEv; readonly evaluationModelConstraints?: readonly (EvalIn | EvalEv)[];
  readonly hostEnvironmentConstraint?: HostIn | HostEv; readonly translationHostEnvironmentConstraint?: HostIn | HostEv; readonly hostEnvironmentConstraints?: readonly (HostIn | HostEv)[]; readonly memoryModelConstraint?: MemIn | MemEv; readonly translationMemoryModelConstraint?: MemIn | MemEv; readonly memoryModelConstraints?: readonly (MemIn | MemEv)[]; readonly metaprogrammingConstraint?: MetaIn | MetaEv; readonly translationMetaprogrammingConstraint?: MetaIn | MetaEv; readonly metaprogrammingConstraints?: readonly (MetaIn | MetaEv)[]; readonly scopeBindingConstraint?: SbIn | SbEv; readonly translationScopeBindingConstraint?: SbIn | SbEv; readonly scopeBindingConstraints?: readonly (SbIn | SbEv)[];
  readonly moduleConstraint?: ModIn | ModEv; readonly translationModuleConstraint?: ModIn | ModEv; readonly moduleConstraints?: readonly (ModIn | ModEv)[]; readonly numericSemanticsConstraint?: NumIn | NumEv; readonly translationNumericSemanticsConstraint?: NumIn | NumEv; readonly numericSemanticsConstraints?: readonly (NumIn | NumEv)[]; readonly textSemanticsConstraint?: TxtIn | TxtEv; readonly translationTextSemanticsConstraint?: TxtIn | TxtEv; readonly textSemanticsConstraints?: readonly (TxtIn | TxtEv)[]; readonly collectionSemanticsConstraint?: ColIn | ColEv; readonly translationCollectionSemanticsConstraint?: ColIn | ColEv; readonly collectionSemanticsConstraints?: readonly (ColIn | ColEv)[];
  readonly serializationSemanticsConstraint?: SerIn | SerEv; readonly translationSerializationSemanticsConstraint?: SerIn | SerEv; readonly serializationSemanticsConstraints?: readonly (SerIn | SerEv)[]; readonly dependencySemanticsConstraint?: DepIn | DepEv; readonly translationDependencySemanticsConstraint?: DepIn | DepEv; readonly dependencySemanticsConstraints?: readonly (DepIn | DepEv)[]; readonly objectModelConstraint?: ObjIn | ObjEv; readonly translationObjectModelConstraint?: ObjIn | ObjEv; readonly objectModelConstraints?: readonly (ObjIn | ObjEv)[]; readonly protocolConstraint?: ProtoIn | ProtoEv; readonly translationProtocolConstraint?: ProtoIn | ProtoEv; readonly protocolConstraints?: readonly (ProtoIn | ProtoEv)[]; readonly typeConstraint?: TyIn | TyEv; readonly translationTypeConstraint?: TyIn | TyEv; readonly typeConstraints?: readonly (TyIn | TyEv)[];
}

export interface UniversalConversionPlanConstraintQuery extends ResQ, LtQ, CfQ, CbQ, AdtQ, BsQ, BcQ, DlQ, EfQ, ConQ, ErrQ, EvalQ, HostQ, MemQ, MetaQ, SbQ, ModQ, NumQ, TxtQ, ColQ, SerQ, DepQ, ObjQ, ProtoQ, TyQ {}
